import prisma from "../db/prisma";

async function main() {
const cards: Array<[string,string,string,string,string,string[],string[],string,string]> = [

// ==========================================
// LLM Expansion (63 cards: 37→100)
// ==========================================

// ---- LLMCore: 大模型基础 (items llm-38~55) ----
["llm-38","llm","Transformer 的 Self-Attention 公式是什么？Q/K/V 分别是什么意思？","Self-Attention = softmax(Q*K^T / sqrt(dk)) * V。Q(Query): 查询向量(我想要什么)。K(Key): 键向量(我有什么)。V(Value): 值向量(实际内容)。Q和K点积计算注意力分数，除以 sqrt(dk) 防止点积过大导致 softmax 梯度消失。Multi-Head: 多个独立 Self-Attention 并行(不同子空间)。","Self-Attention 公式",["LLM","Transformer","Attention"],["Self-Attention","Q","K","V","softmax","sqrt(dk)","Multi-Head","注意力"],"hard","LLMCore"],
["llm-39","llm","Transformer 的 Positional Encoding 原理？绝对位置编码 vs 相对位置编码？","绝对位置编码: 正弦余弦函数编码每个位置。相对位置编码: 编码两个位置之间的相对距离(Transformer-XL/XLNet)。RoPE(旋转位置编码): 将位置信息旋转注入 Q/K 向量，Llama/Qwen/DeepSeek 使用。ALiBi: 在注意力分数上加线性偏置(距离越远偏置越大)。RoPE 是当前主流。","位置编码",["LLM","Transformer","RoPE"],["位置编码","RoPE","ALiBi","正弦余弦","旋转","相对位置","绝对位置","Llama","DeepSeek"],"hard","LLMCore"],
["llm-40","llm","为什么 Transformer 中除以 sqrt(dk)？不除会怎样？","Softmax 对大值敏感: 当 dk 很大时，Q*K^T 的值范围变大→Softmax 梯度趋近于 0 或 1(梯度消失)。除以 sqrt(dk) 缩放了点积的方差，使梯度保持在合理范围。推导: 假设 Q/K 均值为 0 方差为 1，Q*K 的方差为 dk，除以 sqrt(dk) 归一化方差为 1。","sqrt(dk) 原理",["LLM","Transformer","Attention"],["sqrt(dk)","软最大","梯度消失","方差","归一化","点积","Softmax"],"hard","LLMCore"],
["llm-41","llm","LayerNorm 和 BatchNorm 的区别？为什么 Transformer 用 LayerNorm？","BatchNorm: 对 batch 维度归一化(同一特征在不同样本间)，依赖 batch size。LayerNorm: 对 feature 维度归一化(同一样本所有特征)，不依赖 batch size。Transformer 用 LayerNorm 原因: 1)序列长度可变(BatchNorm 不好处理) 2)训练和推理一致 3)不依赖 batch size。Pre-LN vs Post-LN: Pre-LN 训练更稳定。","LayerNorm vs BatchNorm",["LLM","Transformer","归一化"],["LayerNorm","BatchNorm","Pre-LN","Post-LN","归一化","batch","feature","Transformer"],"medium","LLMCore"],
["llm-42","llm","Pre-Norm 和 Post-Norm 有什么区别？当前主流用哪种？","Post-Norm(原始 Transformer): LayerNorm 在残差连接之后(先加残差再做 LN)。Pre-Norm: LayerNorm 放在 Self-Attention/FFN 之前(先做 LN 再计算)。Pre-Norm 训练更稳定(梯度不会爆炸)，不需要 warmup。当前主流(LLaMA/GPT-3/DeepSeek)都用 Pre-Norm。","Pre-Norm vs Post-Norm",["LLM","Transformer","归一化"],["Pre-Norm","Post-Norm","LayerNorm","残差","梯度","warmup","LLaMA","GPT-3"],"medium","LLMCore"],
["llm-43","llm","SwiGLU 激活函数是什么？为什么优于 ReLU？","SwiGLU = Swish(x) * (x * W_g + b_g)。Swish(x) = x * sigmoid(x)。门控线性单元(GLU)+Swish=SwiGLU。优点: 1)平滑非单调(非 0 区间有梯度) 2)门控机制更灵活 3)LLaMA 实验证明优于 ReLU/GELU。当前 LLM(LLaMA/PaLM/DeepSeek)广泛使用 SwiGLU。","SwiGLU 激活函数",["LLM","激活函数","Transformer"],["SwiGLU","Swish","GLU","ReLU","LLaMA","PaLM","门控","非单调"],"medium","LLMCore"],
["llm-44","llm","LLM 的 Tokenizer 有哪些？BPE/WordPiece/SentencePiece 的区别？","BPE(Byte-Pair Encoding): 合并高频字节对，GPT 使用。WordPiece: BPE 变体，用概率选择合并，BERT 使用。SentencePiece: 把空格也当作字符处理(语言无关)，LLaMA/T5 使用。BPE 和 SentencePiece 最常用。Tokenizer 影响: 中文 tokenize 效率(一个字可能多个 token)、OOV 处理。","Tokenizer 对比",["LLM","Tokenizer","基础"],["Tokenizer","BPE","WordPiece","SentencePiece","GPT","BERT","LLaMA","中文分词"],"medium","LLMCore"],
["llm-45","llm","LLM 的 Tokenizer 为什么对中文不友好？如何优化？","中文不友好原因: 1)中文词边界不明确(需要分词) 2)中文常用字较多(需更多 token) 3)BPE 基于字符频次(中文每个字都是 token)。优化: 1)中文友好 tokenizer(如 ChatGLM 的 SPT) 2)扩充中文词表 3)预处理: 先分词再 tokenize。英文 1 token ≈ 0.75 words，中文 1 token ≈ 1.5-2 汉字。","中文 Tokenizer 问题",["LLM","Tokenizer","中文"],["Tokenizer","中文","BPE","分词","ChatGLM","SPT","词表","token"],"medium","LLMCore"],
["llm-46","llm","什么是 KV Cache？为什么能加速推理？","KV Cache: 推理时缓存之前生成 token 的 K/V 矩阵，避免重复计算。自回归生成时，每个新 token 只需计算自己的 Q/K/V(对其他 token 的 K/V 用缓存)。时间复杂度: 无缓存 O(n^2)，有缓存 O(n)。内存瓶颈: KV Cache 随序列长度线性增长(长序列内存压力大)。","KV Cache 原理",["LLM","推理","优化"],["KV Cache","推理","缓存","K","V","自回归","时间复杂度","內存瓶颈"],"hard","LLMInference"],
["llm-47","llm","什么是 MQA/GQA/MHA？各自的优缺点？","MHA(Multi-Head Attention): 每个 Head 独立 Q/K/V(参数多，效果好)。MQA(Multi-Query): 所有 Head 共享 K/V(参数少，推理快)。GQA(Grouped-Query): 分组共享 K/V(折中，LLaMA2 用)。选型: 追求效果 MHA，追求推理速度 MQA，折中 GQA。","MQA/GQA/MHA",["LLM","Attention","推理"],["MHA","MQA","GQA","Multi-Head","Multi-Query","Grouped-Query","LLaMA2","推理"],"hard","LLMInference"],
["llm-48","llm","什么是 FlashAttention？为什么快？","FlashAttention: 利用 GPU 存储层次(SRAM > HBM)优化 Attention 计算。核心: 把 Q/K/V 分块(tiling)→每次只在 SRAM 计算一块→避免把大矩阵写回 HBM(IO 瓶颈)。加速 2-4 倍，内存节省 O(N) vs O(N^2)。FlashAttention-2/3 进一步优化(更细粒度并行)。","FlashAttention",["LLM","Attention","优化"],["FlashAttention","GPU","SRAM","HBM","tiling","IO","分块","FlashAttention-2"],"hard","LLMInference"],
["llm-49","llm","LLM 的量化(Quantization)是什么？INT8/INT4 怎么做到？","量化: 把 FP32/FP16 模型权重压缩为 INT8/INT4。方法: GPTQ(逐层量化+修正)、AWQ(激活感知)、GGUF(CPU 推理)。INT8: 精度损失很小(可用于推理)。INT4: 精度损失增大(需校准数据)。BitsAndBytes: HuggingFace 量化库。QLoRA: 4-bit 量化+LoRA 微调。","LLM 量化",["LLM","量化","推理"],["量化","Quantization","INT8","INT4","GPTQ","AWQ","GGUF","BitsAndBytes","QLoRA"],"hard","LLMInference"],
["llm-50","llm","什么是 Speculative Decoding？怎么加速推理？","推测解码: 用小模型(Draft Model)快速生成 K 个候选 token→大模型(Target Model)并行验证→接受概率高的 token。一次 Target Model 前向验证 K 个 token。加速 2-3 倍(无损生成质量)。vLLM/DeepSpeed 已支持。","Speculative Decoding",["LLM","推理","加速"],["Speculative Decoding","推测解码","Draft Model","Target Model","验证","并行","vLLM","加速"],"hard","LLMInference"],
["llm-51","llm","vLLM 的 PagedAttention 是什么？","vLLM 内存管理: 把 KV Cache 分成固定大小的 block(类似 OS 分页)。PagedAttention: 用页表(Page Table)管理 block 映射→避免内存碎片、减少浪费(近 0% waste)。批量推理: 可高效并行多个请求。比 HuggingFace 吞吐量高 24 倍。","PagedAttention/vLLM",["LLM","推理","vLLM"],["vLLM","PagedAttention","KV Cache","block","分页","页表","内存管理","吞吐量"],"hard","LLMInference"],
["llm-52","llm","LoRA 微调的原理是什么？为什么参数效率高？","LoRA(Low-Rank Adaptation): 冻结原始权重 W，在旁边训练低秩矩阵 A×B(rank r << d)。ΔW = A * B，A 初始高斯分布，B 初始全 0。前向: h = W*x + (A*B)*x。参数量: 2*dim*r，比全参数微调少 1000 倍。QLoRA: LoRA + 4-bit 量化。","LoRA 原理",["LLM","微调","LoRA"],["LoRA","低秩","A","B","微调","冻结","QLoRA","参数效率","rank"],"hard","LLMTraining"],
["llm-53","llm","全参数微调 vs LoRA vs Prefix Tuning vs P-Tuning 对比？","全参数微调: 效果最好但资源大。LoRA: 低秩矩阵，性能接近全参数，参数少。Prefix Tuning: 在输入前加可训练 prefix token。P-Tuning v2: 每层加 prefix(比 v1 效果好)。Adapter: 在 Transformer 层间插入小网络。选型: 常规微调用 LoRA，多任务微调用 Adapter。","微调方法对比",["LLM","微调","PEFT"],["微调","LoRA","Prefix Tuning","P-Tuning","Adapter","全参数","PEFT","参数效率"],"medium","LLMTraining"],
["llm-54","llm","SFT/RLHF/DPO 三种训练方式有什么区别？","SFT(监督微调): 用高质量回答微调(模仿学习)。RLHF: SFT→训练 Reward Model→PPO 强化学习(人类偏好)。DPO(直接偏好优化): 不需要 Reward Model，直接在偏好数据上优化(更简单稳定)。对比: SFT 基础/RLHF 对齐偏好/DPO 更简单。ChatGPT: SFT+RLHF。LLaMA3: SFT+DPO+RLHF。","SFT/RLHF/DPO",["LLM","训练","对齐"],["SFT","RLHF","DPO","Reward Model","PPO","对齐","偏好","ChatGPT","LLaMA3"],"hard","LLMTraining"],
["llm-55","llm","什么是 RLHF 的 Reward Hacking？怎么解决？","Reward Hacking: LLM 学习到如何最大化奖励但不是真正提高质量(如输出过长的回答/重复套话)。解决: 1)KL 散度约束(不偏离原始模型太远) 2)多维度 Reward Model(质量+安全+简洁) 3)人机混合评估 4)DPO 替代 RLHF(无 Reward Model)。","Reward Hacking",["LLM","RLHF","对齐"],["RLHF","Reward Hacking","KL散度","Reward Model","DPO","对齐","安全","评估"],"hard","LLMTraining"],

// ---- LLMApplication: 大模型应用 (items llm-56~65) ----
["llm-56","llm","Prompt Engineering 中的 Chain-of-Thought 如何设计？","CoT 引导 LLM 逐步推理: 在 prompt 中加入 Let us think step by step。Few-shot CoT: 给 2-3 个推理示例。Zero-shot CoT: 只加一句鼓励逐步思考的话。Self-Consistency: 多次采样+投票(多数答案一致选之)。Tree-of-Thought: 探索多条推理路径评估后选最优。","CoT 设计",["LLM","Prompt","CoT"],["CoT","Chain-of-Thought","Few-shot","Zero-shot","Self-Consistency","Tree-of-Thought","逐步推理"],"medium","LLMApplication"],
["llm-57","llm","ICL(In-Context Learning) 是什么？为什么有效？","ICL: 通过 Prompt 中的示例让 LLM 学会新任务(不更新参数)。原理: 1)LLM 在预训练中学会了 in-context pattern 2)Transformer 的 Attention 机制可从上下文中提取模式。影响因素: 示例数量(3-5个最佳)、示例顺序(随机排列)、示例质量(多样性)。","In-Context Learning",["LLM","ICL","Prompt"],["ICL","In-Context Learning","示例","Few-shot","预训练","Attention","模式","多样性"],"medium","LLMApplication"],
["llm-58","llm","Few-shot/One-shot/Zero-shot 的区别？哪种效果最好？","Zero-shot: 不给示例只给指令。One-shot: 给 1 个示例+指令。Few-shot: 给 3-5 个示例+指令。效果: Few-shot > One-shot > Zero-shot。Few-shot 示例数量存在边际效应(超过 10 个提升不大)。技巧: 示例排序(最近邻优先)、示例标签平衡。","Few/One/Zero-shot",["LLM","Prompt","ICL"],["Few-shot","One-shot","Zero-shot","ICL","示例","指令","排序","标签"],"easy","LLMApplication"],
["llm-59","llm","LLM 应用中如何实现缓存降成本？","语义缓存: 对相似问题返回缓存答案(用 Embedding 相似度匹配)。精确缓存: 完全相同问题返回缓存。GPTCache: 开源 LLM 缓存框架。缓存策略: TTL(过期时间)+LFU(淘汰)。成本节省: 热点问题重复查询可节省 50-80% cost。注意: 时间敏感信息不适合缓存。","LLM 缓存策略",["LLM","成本","缓存"],["缓存","语义缓存","精确缓存","GPTCache","TTL","LFU","成本","Embedding"],"medium","LLMApplication"],
["llm-60","llm","如何评估 LLM 的生成质量？自动指标 vs 人工指标？","自动指标: ROUGE(摘要)、BLEU(翻译)、困惑度(Perplexity: 预测下一个 token 的能力)。LLM 评估: G-Eval(用 GPT-4 评估)、MT-Bench(多轮对话)、AlpacaEval。人工指标: 有用性、安全性、流畅度、幻觉率。实际: 开发用自动指标，上线前人工评估。","LLM 评估方法",["LLM","评估","指标"],["评估","ROUGE","BLEU","Perplexity","G-Eval","MT-Bench","AlpacaEval","人工","幻觉率"],"medium","LLMApplication"],
["llm-61","llm","LLM 输出格式不稳定怎么办？怎么约束 JSON 输出？","1)Prompt 明确格式: 在 System Prompt 中指定 JSON Schema 2)response_format: {type:json_object}(OpenAI) 3)Few-shot 示例 4)guided generation(强制词表约束) 5)正则后处理: 提取 JSON 修复尾部逗号。LangChain: PydanticOutputParser。","LLM JSON 约束",["LLM","JSON","结构化"],["JSON","约束","response_format","guided","Pydantic","Schema","Few-shot","后处理"],"medium","LLMApplication"],
["llm-62","llm","LLM 如何做多轮对话？对话历史怎么管理？","消息格式: [system, user, assistant, user, assistant...]。Token 管理: 历史对话累积 token，超过 context 需要截断。截断策略: 保留最近 N 轮、保留系统 prompt+最近对话、摘要压缩旧对话。LangChain: ConversationBufferMemory/ConversationSummaryMemory。","LLM 多轮对话",["LLM","对话","Context"],["多轮对话","消息","system","history","截断","摘要","Token","Context Window"],"medium","LLMApplication"],
["llm-63","llm","如何构建一个 LLM 应用的评测集？","1)收集 50-200 条真实用户问题 2)标注标准答案(人工+LLM as judge) 3)覆盖多类型: 事实查询、推理、创意、安全边界 4)分层: 难/中/易各占 1/3 5)持续更新(新问题加入旧问题淘汰)。自动化: 每次代码变更跑 eval→对比基线→报表。","LLM 评测集构建",["LLM","评估","工程"],["评测集","标注","分层","自动化","基线","持续更新","LLM as judge","eval"],"medium","LLMApplication"],
["llm-64","llm","什么是 LLM 的 Temperature/Top-p/Top-k？怎么调参？","Temperature: 控制随机性(0=确定输出, 1=随机, >1=更随机)。Top-p(Nucleus Sampling): 累计概率≥p 的 token 中采样。Top-k: 只从概率最高的 k 个 token 中采样。实践: 事实查询用 low temp(0-0.3)，创意写作用 high temp(0.7-1.0)。","Temperature/Top-p",["LLM","参数","推理"],["Temperature","Top-p","Top-k","随机性","采样","核采样","确定","创意"],"easy","LLMInference"],
["llm-65","llm","LLM 的推理框架有哪些？vLLM/TGI/llama.cpp/Ollama 区别？","vLLM: 高吞吐(PagedAttention)，适合生产部署。TGI(Text Generation Inference): HuggingFace 官方，兼容性好。llama.cpp: CPU 推理(量化模型 GGUF)，适合边缘设备。Ollama: 一键部署本地 LLM，基于 llama.cpp。选型: 云端高并发 vLLM，本地开发 Ollama，CPU 环境 llama.cpp。","推理框架对比",["LLM","推理","框架"],["vLLM","TGI","llama.cpp","Ollama","推理","部署","PagedAttention","GGUF","CPU"],"medium","LLMInference"],

// ---- LLMTraining: 训练 (items llm-66~75) ----
["llm-66","llm","LLM 的预训练(Pre-training)数据怎么准备？","数据来源: 网页(Common Crawl)、书籍、论文、代码、多语言。数据处理: 1)去重(MinHash) 2)质量过滤(困惑度/分类器) 3)去隐私(PII 脱敏) 4)分词 tokenization。数据混合比例: 高质量数据(书籍/论文)虽少但重复训练多轮。LLaMA: 1.4T tokens，RedPajama: 复刻 LLaMA 数据集。","预训练数据",["LLM","训练","数据"],["预训练","数据","Common Crawl","去重","质量过滤","tokenization","LLaMA","RedPajama"],"medium","LLMTraining"],
["llm-67","llm","什么是 MoE(Mixture of Experts)？为什么大模型用 MoE？","MoE: 多个 Expert(子网络)替代 FFN 层，Router 选择 TopK 个 Expert 激活。稀疏激活: 每次推理只激活部分 Expert(如 2/8)。优势: 总参数量大但计算量小(Mixtral 8x7B=46.7B 参数，激活 12.9B)。DeepSeek-V2 使用 MoE。问题: 负载不均衡(某些 Expert 频繁激活)。","MoE 架构",["LLM","架构","MoE"],["MoE","Mixture of Experts","Router","Expert","稀疏","Mixtral","DeepSeek-V2","负载均衡"],"hard","LLMCore"],
["llm-68","llm","Scaling Law 是什么？对 LLM 训练有什么指导？","Scaling Law(Kaplan/Chinchilla): 模型性能随参数量、数据量、计算量幂律增长。Chinchilla 定律: 最优训练 token 数 ≈ 20 × 参数量(1B 模型用 20B token)。指导: 小模型多数据可能优于大模型少数据。LLaMA3 8B 用 15T token(远超 Chinchilla)。","Scaling Law",["LLM","训练","理论"],["Scaling Law","Kaplan","Chinchilla","参数量","数据量","计算量","幂律","LLaMA3"],"medium","LLMCore"],
["llm-69","llm","LLM 训练中的梯度检查点(Gradient Checkpointing)是什么？","用时间换空间: 前向时不保存所有中间激活(节省内存)，反向时重新计算需要的激活。内存节省约 O(sqrt(L))。PyTorch: torch.utils.checkpoint。几乎所有大模型训练都用。和混合精度+ZeRO 配合使用。","梯度检查点",["LLM","训练","内存"],["梯度检查点","Gradient Checkpointing","重计算","内存","ZeRO","PyTorch","激活","时间换空间"],"medium","LLMTraining"],
["llm-70","llm","ZeRO(零冗余优化器)的三个阶段是什么？","ZeRO-1: 优化器状态分片(每个 GPU 存 1/N 优化器状态)。ZeRO-2: ZeRO-1+梯度分片。ZeRO-3: ZeRO-2+参数分片(每个 GPU 只存 1/N 参数，用时收集)。DeepSpeed ZeRO 实现。ZeRO-3 可训练超大规模模型(万亿参数)。各阶段通信量递增。","ZeRO 优化",["LLM","训练","分布式"],["ZeRO","DeepSpeed","分片","优化器","梯度","参数","GPU","分布式训练"],"hard","LLMTraining"],
["llm-71","llm","什么是分布式训练？数据并行/模型并行/流水线并行？","数据并行(DP): 每个 GPU 有完整模型，数据切分(AllReduce 同步梯度)。模型并行(MP): 模型层切分到不同 GPU(张量并行)。流水线并行(PP): 模型按层切分，不同 GPU 负责不同层(微批次流水)。3D 并行: DP+MP+PP 组合。","分布式训练",["LLM","训练","分布式"],["分布式训练","数据并行","模型并行","流水线并行","3D并行","DP","MP","PP","AllReduce"],"hard","LLMTraining"],
["llm-72","llm","大模型训练中的损失尖刺(Loss Spike)怎么处理？","Loss Spike: 训练中 loss 突然飙升(可能是坏数据/梯度爆炸)。处理: 1)回滚到 spike 前 checkpoint 2)跳过这批数据(resume) 3)减小学习率 4)梯度裁剪(clip grad norm=1.0)。预防: 训练中实时监控 loss 曲线，异常时自动打快照。","Loss Spike 处理",["LLM","训练","稳定性"],["Loss Spike","损失尖刺","回滚","checkpoint","梯度裁剪","学习率","跳数据"],"medium","LLMTraining"],
["llm-73","llm","Megatron-LM 的模型并行怎么实现？","Megatron-LM(NVIDIA): 张量并行(TP)+流水线并行(PP)。TP: 对 Attention/FFN 层的矩阵乘法在行/列维度切分(每个 GPU 计算部分矩阵乘→AllReduce 拼接)。PP: P2P 通信传递激活/梯度。3D 并行: DP+TP+PP 结合。","Megatron-LM",["LLM","训练","分布式"],["Megatron-LM","张量并行","流水线","NVIDIA","Attention","FFN","3D并行","AllReduce"],"hard","LLMTraining"],
["llm-74","llm","LLM 的知识截止日期问题怎么解决？","知识截止日期: LLM 只知道训练截止日前的信息。解决方案: 1)RAG(检索最新文档) 2)微调(增量训练新数据) 3)CoT+搜索(让 LLM 调用搜索工具) 4)实时 API(如天气/股价/新闻). 选型: 需要实时信息用 RAG 或工具调用。","知识截止日期",["LLM","RAG","时效性"],["知识截止","RAG","微调","搜索","实时","增量训练","时效性","工具"],"medium","LLMApplication"],
["llm-75","llm","什么是 LLM 的幻觉(Hallucination)？产生原因和缓解方法？","幻觉: LLM 输出流畅但事实错误的内容。原因: 1)训练数据噪声 2)模型过度泛化 3)缺乏外部知识验证。缓解: 1)RAG(检索事实文档) 2)降低 Temperature 3)Prompt 中明确要求 only use provided information 4)输出自我验证(Self-Consistency) 5)Fine-tuning 减少幻觉。","LLM 幻觉",["LLM","幻觉","安全"],["幻觉","Hallucination","RAG","Temperature","Self-Consistency","Fine-tuning","噪音","泛化"],"medium","LLMApplication"],

// ---- LLMInference: 推理优化 (items llm-76~85) ----
["llm-76","llm","LLM 推理的瓶颈是什么？计算密集还是内存密集？","小 batch: 内存瓶颈(从显存读权重比计算耗时)。大 batch: 计算瓶颈(矩阵乘密集)。自回归生成(Decode 阶段): 内存瓶颈(每个 token 做一次矩阵向量乘，带宽受限)。Prefill 阶段: 计算瓶颈(并行处理所有 prompt token)。优化: 计算阶段用 Tensor Core，内存阶段用 FlashAttention。","推理瓶颈",["LLM","推理","性能"],["推理","瓶颈","内存","计算","Prefill","Decode","带宽","Tensor Core","FlashAttention"],"hard","LLMInference"],
["llm-77","llm","Continuous Batching 是什么？为什么比 Static Batching 好？","Static Batching: 等一批请求全部完成才开始下一批(短板效应)。Continuous Batching: 动态添加/移除请求(一个请求完成立刻补充新请求)。vLLM/TGI 都支持。优势: GPU 利用率高(减少空闲时间)，吞吐量提升 5-10 倍。","Continuous Batching",["LLM","推理","优化"],["Continuous Batching","Static Batching","vLLM","TGI","GPU","吞吐量","动态","短板"],"medium","LLMInference"],
["llm-78","llm","LLM 推理的延迟由什么构成？如何优化？","延迟 = Prompt 处理时间 + Token 生成时间 × Token 数。优化 Prompt: 1)Prefix Caching(缓存公共前缀 KV) 2)Prompt 压缩(去掉冗余)。优化生成: 1)Speculative Decoding 2)量化(INT8/INT4) 3)KV Cache 优化(PagedAttention)。","推理延迟优化",["LLM","推理","延迟"],["延迟","Prompt","Token","Prefix Caching","Speculative Decoding","量化","PagedAttention","KV Cache"],"medium","LLMInference"],
["llm-79","llm","什么是 LLM 的 Prompt Caching/Prefix Caching？","Prefix Caching: 多个请求共享相同的 system prompt/前缀时，只计算一次 KV Cache，后续请求复用。效果: 大幅减少 Prefill 时间(尤其对长 system prompt)。Claude/GPT-4 Turbo 支持自动缓存。","Prompt Caching",["LLM","推理","缓存"],["Prompt Caching","Prefix Caching","KV Cache","system","Prefill","复用","Claude","GPT-4"],"medium","LLMInference"],
["llm-80","llm","LLM 部署时如何做负载均衡和扩缩容？","负载均衡: 基于请求队列长度/RPS 路由到最空闲实例。扩缩容: 根据 GPU 利用率/QPS 自动增减实例(K8s HPA)。模型预热: 启动后先发 warmup 请求(preload 权重到 GPU)。策略: 优先利用已有实例，超出队列阈值时扩容，空闲时缩容。","LLM 部署",["LLM","部署","K8s"],["部署","负载均衡","扩缩容","HPA","warmup","GPU","K8s","实例"],"medium","LLMInference"],
["llm-81","llm","什么是 GGUF/GGML 格式？CPU 推理怎么实现？","GGUF(GGML Unified Format): llama.cpp 的模型格式。特点: CPU 推理(C++ 优化)、量化支持(INT4/INT5/INT8)、mmap 加载(零拷贝)、单文件便携。Ollama 用 GGUF。CPU 推理内存: 7B 模型 INT4 约 4GB，13B 约 7GB。","GGUF/GGML",["LLM","推理","CPU"],["GGUF","GGML","llama.cpp","CPU","量化","mmap","Ollama","INT4"],"medium","LLMInference"],
["llm-82","llm","LLM 推理中如何监控成本和质量？","成本: token 计数(prompt+completion)、API 调用次数、日均费用。质量: 延迟 P50/P95/P99、首 token 时间(TTFT)、生成速度(tokens/s)、幻觉率。工具: LangSmith/LangFuse/Helicone。告警: 延迟突增(>P99)、error rate 升高。","LLM 监控",["LLM","监控","成本"],["监控","成本","延迟","P50","P95","TTFT","tokens/s","LangSmith","Helicone"],"medium","LLMInference"],
["llm-83","llm","什么是 LLM 的 Watermarking(水印)？有什么用？","LLM 水印: 在生成文本中嵌入不可见标记(特定 token 选择模式)。检测: 通过统计检验判断文本是否由特定 LLM 生成。用途: 识别 AI 生成内容(学术诚信)、版权保护。局限: 翻译/改写会破坏水印。","LLM 水印",["LLM","安全","水印"],["LLM","Watermarking","水印","检测","AI内容","学术","版权","token"],"medium","LLMApplication"],
["llm-84","llm","LLM 为什么有时候很聪明有时候很笨？哪些任务不擅长？","擅长: 语言理解、文本生成、翻译、摘要、代码生成、知识问答。不擅长: 多步数学推理(无外部工具)、精确计数、最新事实(知识截止)、因果推理、空间推理、多语言混合。原因: 自回归生成(单向)、统计学习(缺乏真实世界 grounding)。","LLM 能力局限",["LLM","能力","局限"],["LLM","能力","擅长","不擅长","数学","事实","因果","空间","grounding"],"medium","LLMCore"],
["llm-85","llm","GPT/Claude/Gemini/LLaMA/Qwen/DeepSeek 核心差异是什么？","GPT-4: 闭源最强(多模态+Code Interpreter)。Claude: 长上下文(200K)+安全。Gemini: Google 多模态。LLaMA: Meta 开源(社区生态好)。Qwen: 阿里开源、中文能力强。DeepSeek: 国产开源、MoE、高性价比(便宜 10-50x)。选型: 中文用 Qwen/DeepSeek，开源用 LLaMA。","主流 LLM 对比",["LLM","对比","选型"],["GPT","Claude","Gemini","LLaMA","Qwen","DeepSeek","开源","中文","MoE"],"medium","LLMCore"],

// ---- LLMSafety: 安全与对齐 (items llm-86~90) ----
["llm-86","llm","什么是 AI Alignment(对齐)？为什么重要？","AI Alignment: 确保 AI 系统的目标和行为符合人类价值观和意图。三个层面: 1)Instruct Following(遵循指令) 2)Honesty(真实性) 3)Harmlessness(无伤害)。方法: RLHF/DPO/Constitutional AI。不对齐风险: 编造、歧视、危险建议。","AI Alignment",["LLM","安全","对齐"],["Alignment","对齐","Instruct","Honesty","Harmlessness","RLHF","DPO","Constitutional AI"],"medium","LLMSafety"],
["llm-87","llm","什么是 Constitutional AI？和 RLHF 的区别？","Constitutional AI(Anthropic): 用宪法(Constitution)规则指导模型行为。流程: 1)Critique(模型根据 constitution 自评估输出) 2)Revision(根据 critique 修正输出) 3)用修正后的数据做 RLAIF(不需要人类标注)。优势: 可扩展(规则可调整)，减少人类标注成本。","Constitutional AI",["LLM","安全","对齐"],["Constitutional AI","Anthropic","宪法","Critique","Revision","RLAIF","自评估","标注"],"medium","LLMSafety"],
["llm-88","llm","LLM 红队测试(Red Teaming)怎么做？","红队测试: 组织安全团队模拟攻击 LLM(越狱/注入/偏见)。测试用例: 安全数百条 prompts(暴力/色情/歧视/非法)。自动化: 用另一个 LLM(GPT-4)自动生成攻击 prompt。评估: 不安全输出率<0.1%。Meta/Anthropic 在发布前都做大规模红队测试。","Red Teaming",["LLM","安全","测试"],["Red Teaming","红队","安全","越狱","注入","偏见","测试用例","自动化"],"medium","LLMSafety"],
["llm-89","llm","LLM 的偏见(Bias)有哪些？如何度量？","偏见类型: 性别(他/她职业)、种族、年龄、地域、政治。度量: BBQ(Bias Benchmark for QA)、WinoBias。缓解: 1)训练数据平衡 2)RLHF/DPO 对齐 3)prompt 去偏。原则: 承认偏见存在，持续改进但不承诺完美。","LLM 偏见",["LLM","安全","偏见"],["偏见","Bias","性别","种族","BBQ","WinoBias","RLHF","数据平衡"],"medium","LLMSafety"],
["llm-90","llm","LLM 的数据隐私问题怎么处理？","用户数据: 1)API 调用时不用于训练(OpenAI API) 2)数据脱敏(PII 过滤) 3)本地部署(数据不出域)。模型训练: 差分隐私(DP-SGD)保护训练数据。法规: GDPR(被遗忘权)、中国个人信息保护法。","LLM 隐私",["LLM","安全","隐私"],["隐私","PII","脱敏","本地部署","差分隐私","DP-SGD","GDPR","数据"],"medium","LLMSafety"],

// ==========================================
// Deep Learning Expansion (59 cards: 41→100)
// ==========================================

// ---- DLCore: 深度学习基础 (items dl-42~54) ----
["dl-42","deep-learning","神经网络的反向传播(Backpropagation)详细推导？","链式法则: 从输出层 loss 开始，逐层计算梯度并回传。输出层梯度 = dL/dy = y - target。隐藏层梯度 = W^T * delta * fpr(z)(激活函数导数)。参数更新: W = W - lr * dL/dW。PyTorch 的 autograd 自动计算梯度(动态计算图)。","反向传播",["深度学习","基础","反向传播"],["反向传播","Backpropagation","链式法则","梯度","autograd","计算图","lr","参数更新"],"hard","DLCore"],
["dl-43","deep-learning","激活函数对比: Sigmoid/Tanh/ReLU/GELU/Swish 优缺点和适用场景？","Sigmoid(0,1): 梯度消失。Tanh(-1,1): 中心化但仍有梯度消失。ReLU: 计算简单、稀疏激活，但 Dead ReLU(x<0梯度永远0)。Leaky ReLU: 修正 Dead ReLU。GELU: 高斯误差线性单元(Transformer 常用)。Swish: x*sigmoid(x)，平滑非单调。选型: CNN 用 ReLU，Transformer 用 GELU/Swish。","激活函数对比",["深度学习","激活函数"],["激活函数","Sigmoid","Tanh","ReLU","GELU","Swish","LeakyReLU","Dead ReLU","梯度消失"],"medium","DLCore"],
["dl-44","deep-learning","Batch Normalization 的训练和推理有什么区别？","训练: 用当前 batch 的均值和方差归一化(计算每个 batch 的统计量)。推理: 用训练时累积的全局 moving mean/var(固定值)。作用: 加速收敛、稳定训练、轻微正则化。问题: 小 batch 时统计量不准、RNN 不好用。","BatchNorm 训练推理",["深度学习","BatchNorm","归一化"],["BatchNorm","训练","推理","moving mean","batch","全局","小batch","RNN"],"medium","DLCore"],
["dl-45","deep-learning","梯度消失和梯度爆炸的原因和解决方法？","梯度消失: 深层网络中梯度逐层衰减(激活函数导数<1累计乘)。梯度爆炸: 梯度逐层放大(权重>1累计乘)。解决方法: 1)激活函数用 ReLU(正区间梯度为1) 2)BatchNorm/LayerNorm 3)残差连接(ResNet) 4)梯度裁剪(gradient clipping) 5)合适初始化(Xavier/He)。","梯度消失爆炸",["深度学习","训练","稳定性"],["梯度消失","梯度爆炸","ReLU","BatchNorm","残差","梯度裁剪","Xavier","He"],"medium","DLCore"],
["dl-46","deep-learning","权重初始化方法: Xavier 和 He 初始化的原理和适用场景？","Xavier(Glorot): Var(W) = 2/(n_in + n_out)，适合 Sigmoid/Tanh。He(Kaiming): Var(W) = 2/n_in，适合 ReLU(ReLU 使一半神经元失活，需要更大方差补偿)。PyTorch 默认 Kaiming Uniform。正确初始化避免训练初期梯度消失/爆炸。","权重初始化",["深度学习","初始化","训练"],["权重初始化","Xavier","He","Kaiming","Glorot","方差","ReLU","Sigmoid","PyTorch"],"medium","DLCore"],
["dl-47","deep-learning","学习率调度策略有哪些？怎么选择？","Step: 每 N 步衰减。Cosine: 余弦曲线平滑衰减(当前主流)。Warmup: 初始 N 步线性增长学习率(Transformer 训练必备)。ReduceLROnPlateau: 根据 loss 平台自适应衰减(过时)。Cyclical LR: 周期性升降。选型: 大多数用 Cosine+Warmup, Transformer 用 Warmup 防止训练初期不稳定。","学习率调度",["深度学习","训练","优化"],["学习率","Cosine","Warmup","Step","ReduceLROnPlateau","Cyclical","Scheduler","Transformer"],"medium","DLCore"],
["dl-48","deep-learning","迁移学习(Transfer Learning)和微调(Fine-tuning)的区别？","迁移学习: 预训练模型在源任务上学到的知识迁移到目标任务。微调: 特定形式的迁移学习(加载预训练权重→在新数据上继续训练)。CV: ImageNet 预训练模型微调分类。NLP: BERT/GPT 预训练微调下游任务。全参数微调 vs Feature Extraction(冻结 backbone 只训练 classifier)。","迁移学习/微调",["深度学习","训练","迁移学习"],["迁移学习","微调","Fine-tuning","ImageNet","BERT","GPT","冻结","backbone"],"medium","DLCore"],
["dl-49","deep-learning","过拟合有哪些表现？如何防止过拟合？","表现: 训练 loss 低测试 loss 高、训练 accuracy 高测试 accuracy 低。方法: 1)正则化(L1/L2) 2)Dropout 3)数据增强 4)早停(Early Stopping) 5)减小模型容量 6)增加训练数据 7)BatchNorm(轻微正则化) 8)集成学习(Bagging)。","过拟合防止",["深度学习","训练","正则化"],["过拟合","正则化","Dropout","数据增强","Early Stopping","L1","L2","BatchNorm","Bagging"],"medium","DLCore"],
["dl-50","deep-learning","L1 和 L2 正则化的区别？为什么 L1 产生稀疏解？","L1: |w| 的绝对值之和(拉普拉斯先验)，梯度为常数 sign(w)，产生稀疏解(部分权重为 0)→特征选择。L2: w^2 的和(高斯先验)，梯度为 w(权重小时梯度小)→权重衰减但不为 0。几何解释: L1 约束区域是菱形→最优点在坐标轴上(稀疏)。","L1 vs L2",["深度学习","正则化"],["L1","L2","正则化","稀疏","权重衰减","拉普拉斯","高斯","坐标轴","特征选择"],"medium","DLCore"],
["dl-51","deep-learning","数据增强(Data Augmentation)有哪些方法？","图像: 翻转/旋转/裁剪/颜色抖动/CutMix(gamma 校正)/MixUp(线性混合)。文本: 同义词替换/回译/随机删除/随机交换。音频: 变速/加噪声/时间拉伸。AutoAugment: 自动搜索最优增强策略。注意: 增强不能破坏标签语义(数字 6 旋转 180 度成 9)。","数据增强",["深度学习","数据","训练"],["数据增强","翻转","MixUp","CutMix","回译","AutoAugment","增强","标签"],"medium","DLCore"],
["dl-52","deep-learning","Dropout 的原理？训练和推理时的区别？","Dropout: 训练时以概率 p 随机丢弃神经元(输出设为 0，其他神经元权重乘以 1/(1-p)保持期望不变)。推理: 所有神经元都激活(不丢弃)，权重乘以(1-p)补偿。原理: 每次训练的是不同子网络→集成学习效果。p 通常 0.5(隐藏层)、0.2(输入层)。","Dropout 原理",["深度学习","正则化","Dropout"],["Dropout","正则化","训练","推理","集成","子网络","概率","丢弃"],"medium","DLCore"],
["dl-53","deep-learning","什么是梯度裁剪(Gradient Clipping)？","梯度裁剪: 限制梯度的最大范数(clip_grad_norm_)防止梯度爆炸。如果 grad_norm > threshold 则 grad = grad * threshold / grad_norm。threshold 通常 1.0 或 5.0。RNN/LSTM 训练必用(尤其处理长序列)。Transformer 训练也常用。","梯度裁剪",["深度学习","训练","技巧"],["梯度裁剪","clip_grad_norm","梯度爆炸","RNN","LSTM","Transformer","范数","threshold"],"medium","DLCore"],
["dl-54","deep-learning","什么是 Early Stopping？怎么实现？","Early Stopping: 在验证集 loss 不再下降(连续 patience 个 epoch 没有改善)时停止训练，防止过拟合。实现: 每个 epoch 后记录最佳验证 loss→如果连续 N 个 epoch 未改善→停止→恢复最优模型。patience 通常 5-15 个 epoch。","Early Stopping",["深度学习","训练","技巧"],["Early Stopping","验证集","patience","过拟合","最优模型","epoch","loss","停止"],"medium","DLCore"],

// ---- DLArchitecture: CNN/RNN (items dl-55~64) ----
["dl-55","deep-learning","CNN 中的卷积(Convolution)和池化(Pooling)的作用？","卷积: 提取局部特征(边缘/纹理)，参数共享(同一个 kernel 扫描全图)。池化: 降采样(减小特征图尺寸)、增大感受野、提供平移不变性。MaxPooling: 取最大值(保留最强特征)。AvgPooling: 取平均值(平滑)。GlobalAvgPooling: 最后一层替代全连接(ResNet)。","卷积和池化",["深度学习","CNN","计算机视觉"],["CNN","卷积","池化","MaxPooling","AvgPooling","感受野","参数共享","特征图"],"medium","DLArchitecture"],
["dl-56","deep-learning","ResNet 为什么能训练 100+ 层？残差连接原理？","残差连接(Residual Connection): y = F(x) + x(输出=变换+输入直连)。好处: 1)梯度直接流过直连(解决梯度消失) 2)网络退化为恒等映射(保证深层不比浅层差)。Bottleneck: 1x1+3x3+1x1 卷积减少计算量。ResNet50/101/152 使用 Bottleneck。","ResNet 残差",["深度学习","CNN","ResNet"],["ResNet","残差","Bottleneck","恒等映射","梯度","跳跃连接","1x1","退化"],"hard","DLArchitecture"],
["dl-57","deep-learning","RNN/LSTM/GRU 各自解决了什么问题？区别是什么？","RNN: 序列建模，梯度消失(长期依赖问题)。LSTM: 引入门控(遗忘门+输入门+输出门+记忆细胞 c_t)，缓解梯度消失。GRU: 简化 LSTM(更新门+重置门，无记忆细胞)，参数少 1/3，效果接近。选型: 一般用 LSTM 或 GRU(简单序列)，Transformer 替代 RNN 做长序列。","RNN/LSTM/GRU",["深度学习","RNN","序列"],["RNN","LSTM","GRU","遗忘门","输入门","输出门","记忆细胞","梯度消失","Attention"],"hard","DLArchitecture"],
["dl-58","deep-learning","Seq2Seq 和 Attention 机制是什么？","Seq2Seq: Encoder-Decoder 架构(Encoder 编码输入→Decoder 生成输出)。问题: 固定大小 context vector 成为瓶颈。Attention: Decoder 每个 step 动态关注 Encoder 不同位置的隐藏状态(加权求和)。作用: 解决长句信息瓶颈。应用: 机器翻译、摘要。","Seq2Seq/Attention",["深度学习","NLP","Attention"],["Seq2Seq","Encoder","Decoder","Attention","对齐","context","瓶颈","加权和"],"medium","DLArchitecture"],
["dl-59","deep-learning","Transformer 相比 RNN/LSTM 的优势是什么？","1)并行训练: RNN 必须串行(上一步的计算结果依赖下一步)，Transformer 可以一次性并行处理整个序列。2)长距离依赖: Self-Attention 直接计算任意两个 token 的关系(距离为 1)，RNN 需要逐步传递。3)可扩展: Transformer 可以训练更大更多层的模型。代价: 计算复杂度 O(N^2)(比 RNN 的 O(N)大)。","Transformer 优势",["深度学习","Transformer","NLP"],["Transformer","RNN","LSTM","并行","Self-Attention","长距离","O(N^2)","可扩展"],"medium","DLArchitecture"],
["dl-60","deep-learning","DenseNet 的核心思想是什么？和 ResNet 的区别？","DenseNet: 每一层的输入是前面所有层输出的拼接(concat)，不是求和。ResNet: 残差连接(相加)。DenseNet 优势: 特征复用、梯度流动更好、参数更少(每层只需学少量新特征)。ResNet 优势: 计算量更少(加法 vs 拼接)。","DenseNet vs ResNet",["深度学习","CNN","架构"],["DenseNet","ResNet","拼接","相加","特征复用","参数","梯度","concat"],"medium","DLArchitecture"],
["dl-61","deep-learning","MobileNet 为什么适合移动端？深度可分离卷积原理？","MobileNet 用深度可分离卷积: 1)Depthwise(每个通道单独卷积) 2)Pointwise(1x1 卷积融合通道)。计算量: 传统卷积 C*K*K*Cpr*W*H，深度可分离 = C*K*K*W*H + C*Cpr*W*H。约减少 8-9 倍计算量。MobileNetV2 加入倒残差。MobileNetV3 加入 NAS+NetAdapt。","MobileNet 轻量",["深度学习","CNN","移动端"],["MobileNet","深度可分离","Depthwise","Pointwise","轻量","倒残差","NAS","计算量"],"medium","DLArchitecture"],
["dl-62","deep-learning","Vision Transformer(ViT) 的原理？和 CNN 的区别？","ViT: 把图像切成 patches(如 16x16)→线性投影为 token 序列→加 Position Embedding→送入标准 Transformer Encoder→分类头。与 CNN 区别: CNN 用局部归纳偏置(局部性/平移不变性)，ViT 没有归纳偏置需要更多数据预训练。ViT 在大数据集上超越 CNN。","Vision Transformer",["深度学习","CV","Transformer"],["ViT","Vision Transformer","patch","Position Embedding","归纳偏置","CNN","Transformer","大数据"],"hard","DLArchitecture"],
["dl-63","deep-learning","什么是 U-Net？为什么适合图像分割？","U-Net: 对称的 Encoder-Decoder+Skip Connection。Encoder: 逐步下采样提取特征。Decoder: 逐步上采样恢复分辨率。Skip Connection: 将 Encoder 的特征直接复制到 Decoder 对应层(保留位置信息)。适用: 医学图像分割、去噪、Image-to-Image。","U-Net 分割",["深度学习","CV","分割"],["U-Net","分割","Encoder","Decoder","Skip Connection","上采样","医学图像","Image-to-Image"],"medium","DLArchitecture"],
["dl-64","deep-learning","YOLO 系列的发展？YOLOv5/v8/v10 的区别？","YOLOv5: 社区版，易用(Ultralytics)。YOLOv8: 统一检测/分割/分类/姿态(anchor-free)。YOLOv10: NMS-free(无需后处理)+轻量化+双重标签分配(一对多+一对一)。演进: v3 引入 FPN，v4 加入 CSP/Mish，v5 工程化，v8 多任务，v10 端到端。","YOLO 系列",["深度学习","CV","目标检测"],["YOLO","YOLOv5","YOLOv8","YOLOv10","目标检测","NMS","anchor-free","FPN","CSP"],"medium","DLArchitecture"],

// ---- DLAdvanced: 高级主题 (items dl-65~75) ----
["dl-65","deep-learning","GAN 的原理？生成器和判别器怎么训练？","GAN: Generator(生成器)生成假样本→Discriminator(判别器)分辨真/假→两者对抗训练。训练: 交替训练 D 和 G。D 的 loss: 真样本得高分+假样本得低分。G 的 loss: 欺骗 D(让假样本得分高)。问题: 模式崩溃(Mode Collapse)、训练不稳定。改进: WGAN(推土机距离)、StyleGAN。","GAN 原理",["深度学习","GAN","生成模型"],["GAN","生成器","判别器","对抗","Mode Collapse","WGAN","StyleGAN","训练不稳定"],"hard","DLAdvanced"],
["dl-66","deep-learning","VAE(Variational Autoencoder) 的原理？和 GAN 的区别？","VAE: Encoder 输出潜在分布的均值和方差→从中采样得到 latent z→Decoder 重建。Loss = 重建误差 + KL 散度(正则化 z 接近标准正态分布)。GAN: 隐式生成(不显式建模概率分布)。VAE 生成图像模糊(高斯假设局限)，GAN 生成图像清晰(可能不真实)。","VAE 原理",["深度学习","生成模型","VAE"],["VAE","Encoder","Decoder","latent","KL散度","重建","高斯","GAN对比"],"hard","DLAdvanced"],
["dl-67","deep-learning","什么是 Diffusion Model？为什么能生成高质量图像？","Diffusion: 前向过程(逐步加高斯噪声直到纯噪声)→反向过程(学习去噪从纯噪声恢复图像)。训练: 预测每个 step 的噪声(U-Net)。推理: 从纯噪音逐步去噪生成图像(多步采样)。Stable Diffusion: 在潜在空间做 Diffusion(降维加速)。优势: 训练稳定(比 GAN 稳定)、多样性好。","Diffusion Model",["深度学习","生成模型","Diffusion"],["Diffusion","去噪","U-Net","前向","反向","采样","Stable Diffusion","潜在空间"],"hard","DLAdvanced"],
["dl-68","deep-learning","什么是自监督学习(Self-Supervised Learning)？","自监督学习: 从无标签数据中构造监督信号(Pretext Task)。CV: SimCLR(对比学习: 同一图像的两个增强应该相似)、MAE(随机 mask 图像 patch→重建)。NLP: BERT(MLM 随机 mask token→预测)、GPT(预测下一个 token)。优势: 不需要人工标注，大规模预训练。","自监督学习",["深度学习","自监督","预训练"],["自监督","SimCLR","MAE","BERT","MLM","对比学习","Pretext","预训练"],"medium","DLAdvanced"],
["dl-69","deep-learning","对比学习(Contrastive Learning)的核心原理？","核心: 正样本对(同一数据的不同增强)的表示尽可能相似，负样本对(不同数据的表示)尽可能远离。Loss: InfoNCE(Info Noise Contrastive Estimation)。SimCLR: 大 batch 提供足够负样本。MoCo: 动量编码器+队列维护历史负样本。CLIP: 图文对比学习(图片+文本配对的相似度)。","对比学习",["深度学习","对比学习","SSL"],["对比学习","SimCLR","MoCo","CLIP","InfoNCE","正样本","负样本","动量","队列"],"hard","DLAdvanced"],
["dl-70","deep-learning","什么是 CLIP？为什么多模态重要？","CLIP(OpenAI): 图文双塔模型。Image Encoder(ViT/ResNet)+Text Encoder(Transformer)→计算 image-text 对相似度(对比学习)。训练: 4 亿图文对。能力: 零样本分类(不需要微调)。Stable Diffusion 用 CLIP 文本编码器。多模态 = 视觉+语言+其他突破模态边界。","CLIP 多模态",["深度学习","多模态","CLIP"],["CLIP","多模态","双塔","Image Encoder","Text Encoder","零样本","Stable Diffusion","对比学习"],"hard","DLAdvanced"],
["dl-71","deep-learning","NeRF(Neural Radiance Fields) 是什么？","NeRF: 用 MLP 表示 3D 场景。输入: 5D 坐标(x,y,z位置+θ,φ视角)→输出: RGB颜色+密度σ。体渲染(Volume Rendering): 沿光线积分密度和颜色得到像素值。训练: 多视角照片+重建 loss。应用: 3D 重建、新视角合成。","NeRF",["深度学习","CV","3D"],["NeRF","神经辐射场","MLP","体渲染","3D重建","新视角","光线","密度"],"hard","DLAdvanced"],
["dl-72","deep-learning","知识蒸馏(Knowledge Distillation)的原理？","Teacher-Student 模型: 大模型(Teacher)指导小模型(Student)。Student 学习: 1)Teacher 的软标签(softmax 输出分布，比 hard label 包含更多信息) 2)中间层特征对齐。Loss = 交叉熵(hard label) + KL 散度(Teacher soft label 和 Student soft label)。温度(Temperature): T>1 软化 Teacher 输出分布。","知识蒸馏",["深度学习","训练","压缩"],["知识蒸馏","Teacher","Student","Temperature","软标签","hard label","KL散度","模型压缩"],"medium","DLAdvanced"],
["dl-73","deep-learning","混合精度训练(Mixed Precision)的原理？","FP16(半精度)+FP32(单精度)混合训练。前向/反向用 FP16(速度快、显存少)，权重更新用 FP32(精度高)。Loss Scaling: FP16 梯度可能下溢(接近 0)→将 loss 放大 N 倍→反向梯度也放大→更新时除回去。PyTorch: torch.cuda.amp.autocast+GradScaler。加速约 2-3 倍。","混合精度训练",["深度学习","训练","精度"],["混合精度","FP16","FP32","Loss Scaling","GradScaler","autocast","半精度","加速"],"medium","DLAdvanced"],
["dl-74","deep-learning","什么是 NAS(Neural Architecture Search)？","NAS: 自动搜索最优网络结构。三要素: 搜索空间(可选操作)、搜索策略(强化学习/进化/梯度)、性能评估(训完/共享权重)。DARTS: 可微分 NAS(连续松弛搜索空间→梯度优化)。EfficientNet: 用 NAS 搜索出的最优结构。MobileNetV3: NAS+NetAdapt。","NAS 搜索",["深度学习","架构","NAS"],["NAS","架构搜索","搜索空间","强化学习","DARTS","EfficientNet","MobileNetV3","可微分"],"medium","DLAdvanced"],
["dl-75","deep-learning","模型压缩有哪些方法？量化/剪枝/蒸馏对比？","量化: 降低精度(FP32→INT8/INT4)，推理加速。剪枝: 移除不重要权重/通道(结构化/非结构化)，减小模型。蒸馏: Teacher→Student，保留知识。对比: 量化易实现加速显著、剪枝可能需要专用硬件、蒸馏效果最好但需要 Teacher。组合使用: 蒸馏+量化→既小又快。","模型压缩方法",["深度学习","压缩","部署"],["模型压缩","量化","剪枝","蒸馏","INT8","Teacher","FP32","加速"],"medium","DLAdvanced"],

// ---- DLTraining: 训练工程 (items dl-76~85) ----
["dl-76","deep-learning","PyTorch 的 autograd 原理？动态计算图怎么工作？","autograd: 记录每个操作(构建计算图)→反向时链式法则自动求导。每个 Tensor 有 grad_fn 属性(记录创建操作)。动态图: 每次前向新建图(不同于 TensorFlow 1.x 静态图)，灵活易调试。retain_graph: 多次反向时保留图。with torch.no_grad(): 推理时禁止梯度追踪。","PyTorch autograd",["深度学习","PyTorch","框架"],["autograd","PyTorch","计算图","动态图","grad_fn","retain_graph","no_grad","链式法则"],"medium","DLTraining"],
["dl-77","deep-learning","GPU 显存不足怎么办？有哪些优化策略？","1)减小 batch size 2)混合精度训练(FP16) 3)梯度累积(gradient accumulation: 多 mini-batch 累积一次更新) 4)Gradient Checkpointing(重计算换显存) 5)模型并行/流水线并行 6)使用更小模型 7)Offload 到 CPU(ZeRO-Offload)。显存 = 模型参数×精度 + 梯度 + 优化器状态 + 中间激活。","显存优化",["深度学习","GPU","训练"],["显存","GPU","batch size","混合精度","梯度累积","Checkpointing","ZeRO","Offload"],"medium","DLTraining"],
["dl-78","deep-learning","什么是梯度累积(Gradient Accumulation)？","梯度累积: 由于显存限制不能加大 batch size，通过多个小 batch 累积梯度后做一次参数更新。如: bsz=256 显存放不下，切成 4 个 bsz=64 的 mini-batch，4 次 forward/backward 后做一次 optimizer.step()。等效 batch size = mini_batch_size * accumulation_steps。","梯度累积",["深度学习","训练","显存"],["梯度累积","batch size","accumulation","显存","optimizer.step","小batch","更新","等效bsz"],"medium","DLTraining"],
["dl-79","deep-learning","什么是分布式训练的 AllReduce？Ring AllReduce 原理？","AllReduce: 每个 GPU 都有完整的归约结果(如梯度求和)。Ring AllReduce: GPU 排成环状，分 scatter reduce+all gather 两阶段。每次只传给下一个 GPU(带宽高效)，总通信量 = 2(N-1)/N * data_size(N 个 GPU)。Horovod/NCCL 实现。","AllReduce 原理",["深度学习","分布式","训练"],["AllReduce","Ring","scatter reduce","all gather","NCCL","Horovod","通信","环状"],"hard","DLTraining"],
["dl-80","deep-learning","PyTorch Lightning 是什么？有什么优势？","PyTorch Lightning: 在 PyTorch 上的高层封装。优势: 1)训练循环模板化(LightningModule) 2)自动处理 device/分布式/混合精度 3)日志/checkpoint 自动化 4)代码更整洁(工程和研究分离)。适合: 多人协作项目、快速实验迭代。","PyTorch Lightning",["深度学习","PyTorch","框架"],["PyTorch Lightning","LightningModule","分布式","混合精度","checkpoint","模板","训练循环"],"easy","DLTraining"],
["dl-81","deep-learning","什么是模型训练的 Warmup？为什么 Transformer 需要 Warmup？","Warmup: 训练初期学习率线性增长到目标值(如 4000 步从 0 增到 0.001)。作用: 1)模型初期随机不稳定，大学习率可能震荡 2)Post-Norm Transformer 初期梯度大(需要小 lr) 3)Adam 的动量估计初始化不准(需 warmup 矫正)。Pre-Norm 可以减少 warmup 步数。","Warmup 原理",["深度学习","训练","Transformer"],["Warmup","学习率","Transformer","Post-Norm","Adam","震荡","初期","梯度"],"medium","DLTraining"],
["dl-82","deep-learning","什么是模型的 FLOPs 和参数量？怎么计算？","参数量(Params): 模型所有权重总数(Conv: C_out*C_in*K*K; Linear: in*out)。FLOPs: 浮点运算次数(一次乘加算 2 FLOPs)。计算: Conv FLOPs = 2*C_out*C_in*K*K*H_out*W_out。Transformer FLOPs ≈ 2*N*D^2(序列长度 N，维度 D)。指标: 参数量决定显存，FLOPs 决定速度。","FLOPs/Params",["深度学习","性能","计算"],["FLOPs","Params","参数量","浮点","Conv","Linear","Transformer","显存"],"medium","DLTraining"],
["dl-83","deep-learning","什么是 Label Smoothing？","Label Smoothing: 把 hard label([0,1,0]) 替换为 soft label([0.05,0.9,0.05])。公式: y_smooth = (1 - eps)*y + eps/K(eps 如 0.1，K 为类别数)。作用: 防止模型过度自信(softmax 输出极端值)，轻微正则化。图像分类/机器翻译常用。","Label Smoothing",["深度学习","训练","技巧"],["Label Smoothing","hard label","soft label","eps","过度自信","正则化","softmax"],"easy","DLTraining"],
["dl-84","deep-learning","什么是 Focal Loss？什么时候用？","Focal Loss: 解决类别不平衡问题。公式: FL = -alpha*(1 - pt)^gamma * log(pt)。pt: 正确类别的预测概率。gamma: 聚焦参数(2)，降低易分类样本权重。alpha: 类别权重。当 pt 大时(易分类)，(1-pt)^gamma 接近 0→loss 很小。适用: 目标检测(RetinaNet)、正负样本极度不平衡。","Focal Loss",["深度学习","损失函数","不平衡"],["Focal Loss","类别不平衡","gamma","alpha","RetinaNet","正负样本","pt","权重"],"medium","DLAdvanced"],
["dl-85","deep-learning","Swin Transformer 的核心创新是什么？","Swin Transformer: 层次化+Shifted Window。层次化: 像 CNN 一样逐步下采样(Stage1→Stage2→Stage3→Stage4)产生多尺度特征。Shifted Window: 在相邻层之间移动窗口(解决窗口独立不通信的问题)。W-MSA(常规窗口)+SW-MSA(偏移窗口)交替使用。SwinV2: 改进大模型训练稳定性。","Swin Transformer",["深度学习","CV","Transformer"],["Swin","SwinV2","Shifted Window","W-MSA","SW-MSA","层次化","多尺度","下采样"],"hard","DLArchitecture"],

// ---- DLMore (items dl-86~90) ----
["dl-86","deep-learning","什么是知识图谱嵌入(Knowledge Graph Embedding)？","KG Embedding: 把知识图谱的实体和关系映射到低维向量。TransE: head + relation ≈ tail(尾实体=头实体+关系)。TransR: 不同关系在不同空间投影。RotatE: 复数空间旋转。应用: 链接预测、推荐系统、问答。","知识图谱嵌入",["深度学习","知识图谱","Embedding"],["KG Embedding","TransE","TransR","RotatE","知识图谱","链接预测","关系","复数"],"hard","DLAdvanced"],
["dl-87","deep-learning","图神经网络(GNN)的消息传递机制？","GNN: 每个节点聚合邻居节点的特征(Message Passing)。GCN: 邻居平均(邻接矩阵归一化)。GAT: Attention 加权聚合(不同邻居不同权重)。GraphSAGE: 采样邻居(大图可扩展)。公式: h_v^(k+1) = AGGREGATE({h_u^(k): u in N(v)})。应用: 分子性质预测、社交网络、推荐。","GNN 消息传递",["深度学习","GNN","图"],["GNN","GCN","GAT","GraphSAGE","Message Passing","聚合","邻居","Attention"],"hard","DLAdvanced"],
["dl-88","deep-learning","什么是元学习(Meta Learning)？MAML 原理？","元学习(Learning to Learn): 让模型学会快速适应新任务(少量样本)。MAML: 训练一个初始化参数 θ，在新任务上用少量梯度步快速微调。内循环: 在新任务上更新(θ_i = θ - lr*∇L_task)。外循环: meta-update(更新 θ 降低新任务 loss)。MAML 不需要额外参数(Reptile 是简化版)。","元学习/MAML",["深度学习","元学习","Few-shot"],["元学习","MAML","Learning to Learn","Few-shot","内循环","外循环","快速适应","Reptile"],"hard","DLAdvanced"],
["dl-89","deep-learning","ONNX 是什么？为什么需要模型转换？","ONNX(Open Neural Network Exchange): 开放模型格式(微软+Facebook)。训练用 PyTorch/TF→导出 ONNX→推理用 ONNX Runtime/TensorRT/OpenVINO。好处: 跨框架、硬件优化、推理加速。onnx.export() 导出。ops 版本: 不同 opset 支持不同算子。","ONNX 模型转换",["深度学习","部署","ONNX"],["ONNX","模型转换","PyTorch","TensorRT","OpenVINO","ONNX Runtime","opset","导出"],"medium","DLAdvanced"],
["dl-90","deep-learning","深度学习项目中如何管理实验？","实验管理: MLflow(跟踪参数/指标/模型)、Weights & Biases(WandB)(可视化实验对比)。记录: 模型架构、超参数、训练 loss 曲线、验证指标、GPU 利用。版本: Git 管理代码+MLflow 管理模型。TensorBoard: PyTorch/TF 内置可视化。","实验管理",["深度学习","工程","MLflow"],["实验管理","MLflow","WandB","TensorBoard","超参数","模型","Git","可视化"],"easy","DLTraining"],

];
let count = 0;
for (const [id, deckId, question, answer, title, tags, skw, difficulty, sub] of cards) {
  try { await prisma.card.create({ data: { id, deckId, type:"qa", question, answer, title, tags: JSON.stringify(tags), searchKeywords: JSON.stringify(skw), difficulty, source:"manual", subTopic: sub||null } }); count++; } catch(e: any) {}
}
const llmCount = await prisma.card.count({where:{deckId:"llm"}});
const dlCount = await prisma.card.count({where:{deckId:"deep-learning"}});
console.log("Inserted "+count+", LLM: "+llmCount+", DL: "+dlCount);
await prisma.$disconnect();
}
main();
