import prisma from "../db/prisma";
async function main() {
const cards: Array<[string, string, string, string, string, string[], string[], string, string]> = [
// ==========================================
// JavaCore — 基础与进阶 (items 155–170)
// ==========================================
["java-155","java","Java 中 == 比较的是值还是引用？对于基本类型和引用类型分别怎么处理？","== 对于基本类型比较的是值(int/float等)，对于引用类型比较的是栈中的引用地址(堆中对象地址)。想要比较内容用 equals()。包装类Integer在-128~127范围内有缓存池，用==可能为true。","== 与引用",["Java","基础","OOP"],["==","equals","引用","基本类型","Integer缓存","-128","127"],"easy","JavaCore"],
["java-156","java","为什么重写 equals() 必须重写 hashCode()？","HashMap/HashSet等散列集合依赖 hashCode() 定位桶。如果两个对象 equals() 返回 true 但 hashCode 不同，HashMap 会认为它们是不同对象(落在不同桶)，违反一致性。Object 规范: equals 相等则 hashCode 必须相等(反之不必)。","equals与hashCode",["Java","基础","OOP","HashMap"],["equals","hashCode","HashMap","HashSet","一致性","桶","定位"],"easy","JavaCore"],
["java-157","java","Java 的泛型上下界 ? extends 和 ? super 的使用场景？","PECS 原则: Producer Extends(生产者用 extends，只能读不能写)，Consumer Super(消费者用 super，只能写不能读)。List<? extends Fruit> 可以接收 List<Apple> 但不能 add(不确定子类型)。List<? super Apple> 可以 add(new Apple()) 但不能确定取出类型。","泛型通配符 PECS",["Java","泛型","OOP"],["PECS","extends","super","泛型","通配符","生产者","消费者","协变","逆变"],"medium","JavaCore"],
["java-158","java","Java 代理模式和装饰器模式有什么不同？","代理模式: 控制对对象的访问(权限/日志)，被代理对象对调用方透明。装饰器模式: 动态给对象添加功能，调用方要知道装饰器的存在。IO流典型装饰器: BufferedReader(new InputStreamReader(new FileInputStream()))。AOP是代理。","代理vs装饰器",["Java","设计模式","AOP"],["代理模式","装饰器模式","AOP","BufferedReader","动态代理","装饰","透明"],"medium","JavaCore"],
["java-159","java","Java 中 finally 块一定会执行吗？什么情况下不执行？","正常情况下 finally 总会被执行(即使 try/catch 中有 return)。不执行的情况: 1) System.exit(0) 退出 JVM 2) 守护线程中 try-finally，主线程结束时守护线程被强制终止 3) 死循环导致线程卡死 4) JVM crash。","finally 不执行场景",["Java","基础","异常"],["finally","System.exit","守护线程","return","try-catch","JVM crash"],"medium","JavaCore"],
["java-160","java","Java 值传递还是引用传递？能举例说明吗？","Java 只有值传递。基本类型: 传值的副本(不影响原值)。引用类型: 传引用地址的副本(可以通过副本修改对象内容，但不能修改原引用指向的对象)。String 不可变所以看起来像值传递。swap(a,b)不可能实现(无法修改调用方的变量指向)。","值传递还是引用传递",["Java","基础","面试高频"],["值传递","引用传递","副本","swap","不可变","String","内存模型"],"easy","JavaCore"],
["java-161","java","Java 中 clone() 的浅拷贝有什么陷阱？","clone() 默认只复制基本类型字段和引用地址(不复制引用指向的对象)，修改克隆对象的引用字段会影响原对象。深拷贝: 重写 clone() 递归克隆引用字段或使用序列化方案。数组的 clone() 对基本类型数组是深拷贝，对引用数组是浅拷贝。","clone 浅拷贝陷阱",["Java","基础","对象"],["clone","浅拷贝","深拷贝","Cloneable","序列化","数组","递归"],"medium","JavaCore"],
["java-162","java","java.util.Date 为什么被废弃？替代方案是什么？","Date 的问题: 可变(线程不安全)、月份从0开始(0=1月)、API 混乱、时区处理差。JDK8 替代: LocalDate(日期)/LocalTime(时间)/LocalDateTime(日期时间)/ZonedDateTime(带时区)/Instant(时间戳)。DateTimeFormatter 格式化。不可变+线程安全。","Date 被废弃",["Java","时间","JDK8"],["Date","LocalDate","LocalDateTime","ZonedDateTime","DateTimeFormatter","不可变","线程安全","JDK8"],"easy","JavaCore"],
["java-163","java","Java 中如何实现对象的排序？","Comparable: 实现 compareTo() 自然排序。Comparator: 匿名类/Lambda 实现 compare() 外部排序。Collections.sort(list, comparator)。Stream sorted()。多字段排序: Comparator.comparing().thenComparing()。null值处理: Comparator.nullsFirst/nullsLast。","对象排序",["Java","集合","排序"],["Comparable","Comparator","Collections.sort","Stream.sorted","thenComparing","nullsFirst","nullsLast"],"easy","JavaCore"],
["java-164","java","Java 中正则表达式怎么用？常见语法？","java.util.regex.Pattern+Matcher。Pattern.compile(regex)。字符类: \\d数字 \\w单词 \\s空白。量词: * 0~n, + 1~n, ? 0~1, {n}精确n, {m,n} m~n。贪婪/懒惰/独占。捕获组: (...) 通过 group(n) 获取。Matcher.find() 部分匹配, matches() 全匹配。","正则表达式",["Java","基础","工具"],["正则","Pattern","Matcher","捕获组","group","find","matches","字符类","量词"],"easy","JavaCore"],
["java-165","java","Java 中 SPI 机制是什么？ServiceLoader 怎么用？","SPI(Service Provider Interface): 接口定义+外部实现。ServiceLoader.load(接口.class) 扫描 META-INF/services/接口全限定名文件(内容是实现类的全限定名)，反射实例化。JDBC Driver 加载使用了 SPI。Spring Boot 的 spring.factories 也类似 SPI。","SPI 机制",["Java","基础","SPI"],["SPI","ServiceLoader","META-INF","JDBC","反射","接口","spring.factories"],"medium","JavaCore"],
["java-166","java","Java 中对象的强/软/弱/虚引用的使用场景？","强引用(Strong): 普通 new，绝不回收。软引用(Soft): 内存不足才回收，适合图片缓存。弱引用(Weak): 下次 GC 回收，适合 WeakHashMap 缓存、ThreadLocal 的 key。虚引用(Phantom): get()永远 null，配合 ReferenceQueue 跟踪对象回收时间，管理堆外内存。","四种引用场景",["Java","JVM","引用"],["强引用","软引用","弱引用","虚引用","Reference","ReferenceQueue","缓存","ThreadLocal","堆外内存"],"medium","JavaCore"],

// ==========================================
// JavaCollections — 集合框架进阶
// ==========================================
["java-167","java","HashMap 的 hash 方法为什么是 (h = key.hashCode()) ^ (h >>> 16)？","高 16 位与低 16 位异或，让高位参与取模计算，降低哈希冲突。因为 HashMap 的容量是 2 的幂，取模用 (n-1) & hash，如果只用低 16 位则高位完全没参与。扰动函数只在 JDK8 做一次异或(JDK7 做四次)。","HashMap hash 算法",["Java","集合","HashMap"],["HashMap","hash","扰动函数","异或","高16位","低16位","取模","哈希冲突"],"medium","JavaCore"],
["java-168","java","TreeMap 的底层是什么？有序 Map 的实现对比？","TreeMap: 红黑树，key 自然顺序或 Comparator，O(log n)。LinkedHashMap: HashMap + 双向链表，保持插入顺序或访问顺序(LRU 缓存)。ConcurrentSkipListMap: 跳表实现，线程安全，有序。选择: 需要排序用 TreeMap，需要插入顺序用 LinkedHashMap，高并发有序用 ConcurrentSkipListMap。","有序 Map 对比",["Java","集合","TreeMap"],["TreeMap","LinkedHashMap","ConcurrentSkipListMap","红黑树","跳表","LRU","有序","线程安全"],"medium","JavaCore"],
["java-169","java","Java 中如何实现一个固定大小的队列？","使用 ArrayBlockingQueue(capacity)有界阻塞队列。普通队列: new LinkedBlockingQueue(capacity)。非阻塞有界: 自己封装 LinkedList 或数组，offer/poll 时判断 size。Guava: EvictingQueue.create(maxSize) 自动移除最早元素。环形队列: RingBuffer(Disruptor 使用)。","固定大小队列",["Java","集合","队列"],["队列","ArrayBlockingQueue","LinkedBlockingQueue","EvictingQueue","RingBuffer","Disruptor","有界","容量"],"medium","JavaCore"],
["java-170","java","ArrayList 线程不安全体现在哪里？如何解决？","多线程同时扩容时可能 ArrayIndexOutOfBoundsException 或 数据被覆盖(null)。方案: 1) Collections.synchronizedList(new ArrayList()) 包装同步 2) CopyOnWriteArrayList 写时复制(读多写少) 3) Vector(老旧不推荐) 4) 手动加 synchronized。","ArrayList 线程安全",["Java","集合","并发"],["ArrayList","线程不安全","CopyOnWriteArrayList","synchronizedList","扩容","并发修改","Vector"],"medium","JavaCore"],

// ==========================================
// JavaConcurrency — 并发高级
// ==========================================
["java-171","java","synchronized 锁升级的过程是怎样的？","无锁→偏向锁(记录线程ID，同一线程进入不 CAS)→轻量级锁(自旋 CAS 竞争)→重量级锁(操作系统的 mutex，阻塞挂起)。JDK15 默认关闭偏向锁(延迟 4s)。轻量级锁适合锁持有时间短的场景，重量级锁适合锁竞争激烈或持有时间长的场景。","synchronized 锁升级",["Java","并发","锁","JVM"],["synchronized","锁升级","偏向锁","轻量级锁","重量级锁","自旋","CAS","mutex","JDK15"],"hard","JavaCore"],
["java-172","java","如何设计一个支持超时的分布式锁？","Redisson RLock.tryLock(waitTime, leaseTime, unit): waitTime 等待超时, leaseTime 持有超时。Redis: SET key value NX PX ttl 实现单次获取。续期: Redisson Watch Dog 自动续期。超时释放: 设置合理的 TTL 防止死锁，但 TTL 需大于业务执行时间(考虑 GC 停顿)。","分布式锁超时设计",["Java","分布式","锁","Redis"],["分布式锁","超时","Redisson","tryLock","Watch Dog","TTL","SETNX","死锁","续期"],"hard","JavaAdvanced"],
["java-173","java","线程池被填满后会发生什么？如何监控？","提交策略取决于 RejectedExecutionHandler: AbortPolicy 抛异常(默认), CallerRunsPolicy 由调用线程执行, DiscardPolicy 静默丢弃, DiscardOldestPolicy 丢弃最老任务。监控: 线程池的 getActiveCount()/getQueue().size()/getCompletedTaskCount()。Actuator metrics 也可以暴露。","线程池满处理",["Java","并发","线程池"],["线程池","RejectedExecutionHandler","AbortPolicy","CallerRunsPolicy","DiscardPolicy","监控","getActiveCount"],"medium","JavaCore"],
["java-174","java","CyclicBarrier 和 CountDownLatch 在实际项目中怎么用？","CountDownLatch: 主线程等待多个子线程完成。例如: 并发调用多个 RPC 接口，等所有返回后再汇总。CyclicBarrier: 多个线程互相等待到齐后一起执行。例如: 多线程计算矩阵，每轮计算等所有线程完成后再开始下一轮。Latch 是一次性的，Barrier 可重复。","Latch/Barrier 实战",["Java","并发","JUC"],["CountDownLatch","CyclicBarrier","实战","并发调用","RPC","汇总","矩阵计算","可重置"],"medium","JavaCore"],
["java-175","java","Phaser 是什么？和 CyclicBarrier 的区别？","Phaser(JDK7): 更灵活的同步屏障。支持动态注册/注销参与者，支持分阶段执行。arriveAndAwaitAdvance() 等待同阶段其他参与者。CyclicBarrier 固定参与者数。Phaser 适合任务数量动态变化的场景(如递归分治 Fork/Join)。","Phaser 详解",["Java","并发","JUC"],["Phaser","CyclicBarrier","动态注册","arriveAndAwaitAdvance","分阶段","ForkJoin","同步屏障"],"hard","JavaCore"],

// ==========================================
// JVM — (items 176-182)
// ==========================================
["java-176","java","JVM 怎么判断一个对象是否可回收？","可达性分析: 从 GC Roots(栈帧局部变量/静态变量/JNI 引用)出发，不可达的对象标记为可回收。引用计数法: 有循环引用问题(JVM 不用)。finalize() 自愈: 可被回收对象如果在 finalize() 中重新建立引用可复活(仅一次)，JDK9 废弃。","GC 可达性",["Java","JVM","GC"],["可达性分析","GC Roots","引用计数","finalize","标记清除","不可达","复活"],"medium","JavaCore"],
["java-177","java","G1 垃圾收集器的 Region 和 Mixed GC 是什么？","G1 把堆划分为大小相等的 Region(1~32MB)。Young GC: 只回收新生代 Region。Mixed GC: 回收所有新生代 + 部分老年代(垃圾比例高的)。全局并发标记: 标记老年代中存活对象少的 Region。G1 目标是平衡吞吐量和延迟，JDK9+ 默认。","G1 GC 详解",["Java","JVM","GC","面试高频"],["G1","Region","Mixed GC","Young GC","RSet","SATB","并发标记","吞吐量","延迟"],"hard","JavaCore"],
["java-178","java","ZGC 的特点和适用场景？","ZGC(JDK11实验, JDK15正式): 超低延迟(<10ms，最大不超过1ms)。染色指针(Colored Pointers): 在指针中存储 GC 状态。读屏障(Load Barrier): 读对象时自愈。并发: 除了初始标记几乎全部并发。适用: 大堆(>100G)+低延迟场景。","ZGC 详解",["Java","JVM","GC","ZGC"],["ZGC","低延迟","染色指针","读屏障","并发","大堆","Colored Pointers","Load Barrier"],"hard","JavaCore"],
["java-179","java","JVM 的逃逸分析是什么？有哪些优化？","逃逸分析: 分析对象作用域，未逃逸的方法局部对象可优化。优化: 1)栈上分配(对象生命周期跟随方法，无需 GC) 2)标量替换(把对象拆成基本类型成员) 3)锁消除(对象只被单线程访问去掉锁)。-XX:+DoEscapeAnalysis 默认开启。","逃逸分析",["Java","JVM","优化"],["逃逸分析","栈上分配","标量替换","锁消除","DoEscapeAnalysis","方法逃逸","线程逃逸"],"hard","JavaCore"],
["java-180","java","如何动态调整线程池参数？Java 如何优雅关闭线程池？","shutdown(): 不再接受新任务，已提交任务执行完。shutdownNow(): 尝试中断正在执行的任务并返回未执行任务列表。awaitTermination(timeout, unit): 等待所有任务完成。动态调整: ThreadPoolExecutor.setCorePoolSize()/setMaximumPoolSize() 可在运行时调整。","线程池关闭",["Java","并发","线程池"],["shutdown","shutdownNow","awaitTermination","setCorePoolSize","setMaximumPoolSize","优雅关闭","动态调整"],"medium","JavaCore"],
["java-181","java","查看 JVM 默认参数的命令是什么？","java -XX:+PrintFlagsFinal: 打印所有 JVM 参数及最终值。java -XX:+PrintCommandLineFlags: 打印命令行设置的参数。jinfo <pid>: 查看运行中 JVM 的参数。常见默认: -XX:MaxHeapSize(RAM/4)、-XX:+UseG1GC(JDK9+)、-XX:+UseCompressedOops(堆<32G开启)。","JVM 默认参数",["Java","JVM","调优"],["PrintFlagsFinal","PrintCommandLineFlags","jinfo","MaxHeapSize","UseG1GC","UseCompressedOops","默认参数"],"medium","JavaCore"],
["java-182","java","Java 类的加载时机是什么？哪些情况会触发类加载？","主动引用: new 对象、访问静态变量(非 final)、调用静态方法、反射 Class.forName()、子类初始化先加载父类。被动引用: 子类访问父类静态变量(只加载父类)、定义数组(不加载元素类)、引用常量(编译期常量不触发初始化)。","类加载时机",["Java","JVM","类加载"],["类加载","初始化","new","静态变量","反射","Class.forName","主动引用","被动引用"],"medium","JavaCore"],

// ==========================================
// Spring 核心 — (items 183-193)
// ==========================================
["java-183","java","@Configuration 的 proxyBeanMethods 属性的作用？","proxyBeanMethods=true(默认): CGLIB 代理配置类，同类中调用 @Bean 方法返回同一实例(保证单例)。proxyBeanMethods=false(Lite 模式): 不生成 CGLIB 代理，同类中调用 @Bean 方法每次返回新实例。Lite 模式启动更快(不需要代理)，适合不需要单例保证的场景。","proxyBeanMethods",["Java","Spring","配置"],["@Configuration","proxyBeanMethods","CGLIB","Lite模式","@Bean","单例","代理"],"medium","JavaSpring"],
["java-184","java","Spring 中 @Primary 和 @Qualifier 的使用场景？","@Primary: 多个同类型 Bean 时标注默认首选。@Qualifier: 按名称精确指定注入哪个 Bean。@Resource(name=\"xxx\"): 按名称注入。场景: 多数据源 @Primary 默认 + @Qualifier 指定使用哪个数据源。","@Primary/@Qualifier",["Java","Spring","注解"],["@Primary","@Qualifier","@Resource","多数据源","默认Bean","按名称","按类型","注入"],"easy","JavaSpring"],
["java-185","java","Spring Boot 的 @Conditional 注解有哪些常用实现？","@ConditionalOnClass: 类存在时生效。@ConditionalOnMissingBean: Bean 不存在时生效。@ConditionalOnProperty: 配置项满足时生效。@ConditionalOnExpression: SpEL 表达式。@ConditionalOnWebApplication: Web环境。@ConditionalOnBean: Bean存在时生效。底层: Condition 接口 matches()。","@Conditional 注解",["Java","Spring Boot","条件"],["@Conditional","@ConditionalOnClass","@ConditionalOnMissingBean","@ConditionalOnProperty","@ConditionalOnExpression","SpEL","自动配置"],"medium","JavaSpring"],
["java-186","java","Spring 的 BeanFactory 和 ApplicationContext 的区别？","BeanFactory: 最基础的 IoC 容器，懒加载(第一次 getBean 才创建)。ApplicationContext: 继承 BeanFactory，启动时预实例化所有单例 Bean(饿汉)，提供国际化、事件发布、资源加载、AOP 等企业级功能。项目都用 ApplicationContext。","BeanFactory vs ApplicationContext",["Java","Spring","IoC"],["BeanFactory","ApplicationContext","IoC","懒加载","预实例化","事件","国际化","AOP"],"medium","JavaSpring"],
["java-187","java","Spring Boot 如何自定义 Starter？","步骤: 1) 创建 autoconfigure 模块，定义 @Configuration 类，使用 @Conditional 控制条件 2) 创建 META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 文件声明配置类 3) 创建 starter 模块(pom 依赖 autoconfigure) 4) application.yml 中可配置自定义属性。","自定义 Starter",["Java","Spring Boot","Starter"],["Starter","autoconfigure","AutoConfiguration","@Conditional","META-INF","spring.factories","自定义"],"medium","JavaSpring"],
["java-188","java","@RestController 和 @Controller 的区别？","@RestController = @Controller + @ResponseBody。所有方法返回值直接写入 HTTP 响应体(JSON/XML)。@Controller 的方法返回值默认走 ViewResolver 解析视图(.html/.jsp)，加 @ResponseBody 才能返回数据。","@RestController vs @Controller",["Java","Spring MVC","注解"],["@RestController","@Controller","@ResponseBody","ViewResolver","JSON","视图","REST"],"easy","JavaSpring"],
["java-189","java","Spring Boot 支持哪些外部化配置？优先级是怎样的？","优先级(高→低): 命令行参数→Servlet 参数→JNDI→系统环境变量→application-{profile}.yml→application.yml→@PropertySource。Spring Boot 默认加载: application.yml/properties。配置加密: Jasypt。@Value 注入单个，@ConfigurationProperties 注入一组。","外部化配置",["Java","Spring Boot","配置"],["外部化配置","优先级","application.yml","@Value","@ConfigurationProperties","Jasypt","加密","命令行"],"medium","JavaSpring"],
["java-190","java","Spring Boot 的 @Profile 注解怎么用？","@Profile(\"dev\"/\"prod\"/\"test\") 标注类或方法，激活对应 profile 时生效。启动: spring.profiles.active=prod。多文档: application.yml 中用 --- 分隔不同 profile。@Profile(\"!prod\") 排除。","@Profile 注解",["Java","Spring Boot","环境"],["@Profile","spring.profiles.active","环境隔离","dev","prod","多文档","---分隔"],"easy","JavaSpring"],
["java-191","java","Spring 如何用 @Retryable 实现重试？","spring-retry 依赖。@EnableRetry 开启。@Retryable(value=Exception.class, maxAttempts=3, backoff=@Backoff(delay=2000, multiplier=2))。@Recover 定义重试耗尽后的降级方法。不支持同类内部调用(代理失效)。替代: Resilience4j Retry。","@Retryable 重试",["Java","Spring","重试"],["@Retryable","@EnableRetry","@Recover","spring-retry","backoff","Resilience4j","maxAttempts","降级"],"medium","JavaSpring"],
["java-192","java","Spring Cache 抽象的使用和原理？","@EnableCaching 开启。@Cacheable: 方法结果缓存。@CachePut: 更新缓存。@CacheEvict: 清除缓存。@Caching: 组合多个缓存操作。缓存实现: Caffeine(本地)、Redis(分布式)。key 表达式: SpEL(#参数名)。condition/unless 控制缓存条件。","Spring Cache",["Java","Spring","缓存"],["@Cacheable","@CachePut","@CacheEvict","@EnableCaching","Caffeine","Redis","SpEL","key"],"medium","JavaSpring"],
["java-193","java","Spring Boot 中如何实现请求参数的前置校验？","Controller 方法参数用 @Valid/@Validated + 注解(@NotNull/@Size/@Email)。全局异常: @RestControllerAdvice+@ExceptionHandler(MethodArgumentNotValidException.class) 统一返回校验错误。分组校验: @Validated(Group.class)。自定义校验器: ConstraintValidator。","请求参数校验",["Java","Spring Boot","校验"],["@Valid","@Validated","@RestControllerAdvice","ConstraintValidator","MethodArgumentNotValidException","分组校验","全局异常"],"medium","JavaSpring"],

// ==========================================
// 数据库/MyBatis — (items 194-202)  
// ==========================================
["java-194","java","MySQL 的覆盖索引是什么？如何利用覆盖索引优化查询？","覆盖索引: 查询的字段全部在索引中，不需要回表查聚簇索引。EXPLAIN 的 Extra 列显示 Using index 表示覆盖索引。优化: SELECT 只查需要的列、建立联合索引覆盖 WHERE + SELECT 字段。缺点是索引变大(冗余字段)。","覆盖索引",["Java","MySQL","索引"],["覆盖索引","回表","Using index","EXPLAIN","联合索引","冗余字段","聚簇索引"],"medium","JavaDatabase"],
["java-195","java","MySQL 的 change buffer 是什么？有什么作用？","change buffer 是 InnoDB 内存结构，用于缓存对非唯一二级索引的修改(insert/update/delete)。当目标页不在 Buffer Pool 时先写入 change buffer，页被读到内存时再合并。减少随机 IO，适合写多读少的场景。唯一索引不能使用 change buffer。","change buffer",["Java","MySQL","InnoDB"],["change buffer","InnoDB","二级索引","Buffer Pool","随机IO","合并","唯一索引","写多读少"],"hard","JavaDatabase"],
["java-196","java","SQL 优化的执行计划怎么看？type 列有哪些值？","type(访问类型): system>const>eq_ref>ref>range>index>ALL。ALL(全表扫描最差)、index(全索引扫描)、range(索引范围)、ref(非唯一索引等值)、eq_ref(唯一索引等值)、const(主键等值)。rows: 扫描行数估算。Extra: Using filesort(文件排序)、Using temporary(临时表)需要优化。","EXPLAIN type",["Java","MySQL","SQL优化"],["EXPLAIN","type","ALL","ref","range","const","eq_ref","Using filesort","Using temporary","rows"],"medium","JavaDatabase"],
["java-197","java","数据库死锁怎么排查和解决？","排查: SHOW ENGINE INNODB STATUS 查看 LATEST DETECTED DEADLOCK 段。MySQL 自动检测死锁并回滚事务(持有最少行锁的事务)。日志: innodb_print_all_deadlocks=ON。解决: 统一加锁顺序、缩短事务时间、使用乐观锁替代悲观锁、降低隔离级别。","数据库死锁",["Java","MySQL","死锁","面试高频"],["死锁","INNODB STATUS","加锁顺序","乐观锁","悲观锁","隔离级别","回滚","事务"],"medium","JavaDatabase"],
["java-198","java","MyBatis 和 MyBatis-Plus 有什么区别？","MyBatis: 半自动 ORM，手写 XML SQL。MyBatis-Plus: 在 MyBatis 基础上增强，提供内置 CRUD(BaseMapper)、条件构造器(LambdaQueryWrapper)、分页插件(PaginationInterceptor)、乐观锁、逻辑删除等。优点: 减少样板代码。缺点: 复杂查询仍需手写 SQL。","MyBatis vs MyBatis-Plus",["Java","MyBatis","ORM"],["MyBatis","MyBatis-Plus","BaseMapper","LambdaQueryWrapper","分页","乐观锁","逻辑删除","条件构造器"],"medium","JavaORM"],
["java-199","java","JDBC 的 PreparedStatement 为什么能防止 SQL 注入？","PreparedStatement 预编译 SQL，参数用 ? 占位符，数据库编译 SQL 后再传参数值，参数值不会作为 SQL 的一部分执行。Statement 拼接字符串则会把恶意 SQL 片段(1 OR 1=1)当作 SQL 执行。原理: 编译和执行分离。","PreparedStatement 防注入",["Java","JDBC","安全"],["PreparedStatement","SQL注入","预编译","占位符","Statement","编译","分离","安全"],"easy","JavaORM"],
["java-200","java","什么是数据库的读写分离？如何实现？","写主库、读从库，减轻主库压力。框架: ShardingSphere 读写分离。AbstractRoutingDataSource: Spring 动态数据源。问题: 主从延迟导致读到旧数据，刚写完的关键读强制走主库。GTID: MySQL 5.6+ 全局事务 ID，主从同步追踪。","数据库读写分离",["Java","数据库","架构"],["读写分离","主从","AbstractRoutingDataSource","ShardingSphere","GTID","延迟","动态数据源"],"medium","JavaDatabase"],

// ==========================================
// Redis/缓存 — (items 201-206)
// ==========================================
["java-201","java","Redis 的 Bitmap 和 HyperLogLog 的用途？","Bitmap: 位图操作(setbit/getbit/bitcount)，适合签到统计、用户在线状态。HyperLogLog: 基数统计(pfadd/pfcount)，占 12KB 内存，误差 0.81%，适合 UV 统计。Bloom Filter(RedisBloom 模块): 判断元素是否存在(有误判率)，适合缓存穿透、黑名单。","Redis Bitmap/HLL",["Java","Redis","数据结构"],["Bitmap","HyperLogLog","Bloom","UV","签到","基数","setbit","pfadd","pfcount"],"medium","JavaRedis"],
["java-202","java","Redis 实现分布式锁时，如何避免误删别人的锁？","判断锁的 value 是否是自己设置的(通常 UUID): get(key) == myValue 再 del(key)，用 Lua 脚本保证原子性。Redisson 的 RLock.unlock() 内置持有者判断。value 设计: UUID + 线程ID。不要用固定的 lock value。","避免误删锁",["Java","Redis","分布式锁"],["分布式锁","误删","UUID","Lua","Redisson","RLock","原子","value"],"medium","JavaRedis"],
["java-203","java","Redis 的 GEO 数据结构和应用？","GEOADD 添加经纬度坐标。GEORADIUS/GEOSEARCH 半径搜索。GEODIST 计算距离。底层: ZSet(score=Mercator 投影)。GeoHash: 将二维坐标编码为一维字符串，前缀越接近距离越近。应用: 附近的人、附近商家。","Redis GEO",["Java","Redis","数据结构"],["GEO","GEOADD","GEORADIUS","GEOSEARCH","ZSet","GeoHash","附近的人","坐标"],"medium","JavaRedis"],
["java-204","java","Redis Stream 是什么？和 Kafka 的区别？","Stream(Redis 5.0): 持久化的消息队列。XADD 追加消息，XREAD 消费，XGROUP 消费者组。消息确认: XACK。和 Kafka: Stream 简单，无分区概念(但可以多 Stream)、轻量级。适合轻量级消息队列，大数据量用 Kafka。","Redis Stream",["Java","Redis","消息队列"],["Redis","Stream","XADD","XREAD","XGROUP","XACK","消费者组","消息队列","Kafka对比"],"hard","JavaRedis"],
["java-205","java","本地缓存 Caffeine 的 W-TinyLFU 算法原理？","Caffeine 近优淘汰算法。窗口缓存(Window TinyLFU): 1%容量作为窗口，新数据先入窗口。主缓存: SLRU(Segmented LRU) 分为 probation(试用)和 protected(保护)。Count-Min Sketch 估算访问频率。淘汰: probation 数据频率低于窗口数据则被替换。","Caffeine W-TinyLFU",["Java","缓存","Caffeine"],["Caffeine","W-TinyLFU","Window","SLRU","probation","protected","Count-Min Sketch","淘汰"],"hard","JavaRedis"],
["java-206","java","缓存和数据库的一致性问题怎么解决？","Cache Aside: 先更新数据库，再删除缓存(不是更新缓存)。延迟双删: 删缓存→更新DB→等一会再删一次。读写锁: 更新时加锁。Canal 监听 Binlog: 异步更新缓存。最终一致性: 缓存设置合理的过期时间兜底。","缓存DB一致性",["Java","缓存","数据库"],["缓存一致","Cache Aside","延迟双删","Canal","Binlog","过期时间","最终一致","读写锁"],"medium","JavaRedis"],
];

let count = 0;
for (const [id, deckId, question, answer, title, tags, skw, difficulty, sub] of cards) {
  try {
    await prisma.card.create({ data: { id, deckId, type: "qa", question, answer, title, tags: JSON.stringify(tags), searchKeywords: JSON.stringify(skw || []), difficulty, source: "manual", subTopic: sub || null } });
    count++;
  } catch(e: any) { if (!e.message?.includes("Unique")) console.warn("Skip " + id + ": " + e.message?.slice(0, 60)); }
}

console.log("Inserted " + count + " / " + cards.length + " cards");
console.log("Total Java cards now: " + (54 + count));
await prisma.$disconnect();

}
main();
