import prisma from "../db/prisma";

async function main() {
const cards: Array<[string, string, string, string, string, string[], string[], string, string]> = [
// JVM (items 246-252)
["java-246","java","JVM 的类卸载发生在什么情况下？","类卸载需要同时满足: 1)该类的所有实例已被回收 2)该类的 ClassLoader 已被回收 3)该类的 Class 对象没有被引用。条件苛刻，所以基于 JDK 动态代理的类可能堆积在 Metaspace。-XX:+TraceClassUnloading 跟踪卸载。","类卸载",["Java","JVM","类加载"],["类卸载","ClassLoader","Metaspace","动态代理","GC","TraceClassUnloading","实例回收"],"hard","JavaCore"],
["java-247","java","JVM 的 TLAB 是什么？为什么需要 TLAB？","TLAB(Thread Local Allocation Buffer): 每个线程在 Eden 区预分配一小块私有的分配缓冲区。多线程创建对象时不用竞争全局指针，减少同步开销。-XX:+UseTLAB 默认开启。-XX:TLABSize 调整大小。大对象直接进老年代(PretenureSizeThreshold)。","TLAB",["Java","JVM","内存"],["TLAB","Eden","线程","分配缓冲区","竞争","PretenureSizeThreshold","大对象","UseTLAB"],"hard","JavaCore"],
["java-248","java","如何查看和分析 Java 线程死锁？","jstack <pid> 会打印死锁信息(Found one Java-level deadlock)。jvisualvm 线程 Dump 并检测死锁。Arthas: thread -b 查找死锁。JConsole: 线程 Tab 自动检测。死锁日志: 包含线程名、锁住的资源、等待的资源。","线程死锁查看",["Java","并发","工具"],["死锁","jstack","jvisualvm","Arthas","thread -b","JConsole","线程Dump","BLOCKED"],"medium","JavaCore"],
["java-249","java","Java 程序启动慢怎么排查？","类加载: -XX:+TraceClassLoading 查看加载耗时。Spring Bean 初始化: Actuator metrics。JIT 编译: -XX:+PrintCompilation。CDS(AppCDS) 预存类元数据加速启动。GraalVM Native Image: AOT 编译秒启动。减少扫描路径: @ComponentScan 限定包路径。","启动慢排查",["Java","性能","Spring Boot"],["启动慢","TraceClassLoading","CDS","AppCDS","GraalVM","Native Image","ComponentScan","PrintCompilation"],"medium","JavaCore"],
["java-250","java","什么是伪共享(False Sharing)？如何避免？","伪共享: 多线程修改了同一个缓存行(64字节)的不同变量，导致缓存一致性协议频繁失效(不停回写主存)。@Contended(JDK8) 注解自动填充缓存行。手动: 变量前后加 7 个 long 变量填充。Disruptor 大量使用填充避免伪共享。","伪共享",["Java","并发","性能"],["伪共享","False Sharing","缓存行","@Contended","Disruptor","填充","64字节","缓存一致性"],"hard","JavaCore"],

// SpringBoot (items 251-257)
["java-251","java","Spring Boot 如何加载 application.yml？优先级？","ConfigFileApplicationListener 监听 ApplicationEnvironmentPreparedEvent，加载 classpath 下的 application.yml/properties。顺序: classpath:/,classpath:/config/,file:./,file:./config/。Profile 覆盖: application-{profile}.yml 覆盖 application.yml。","application.yml 加载",["Java","Spring Boot","配置"],["application.yml","ConfigFileApplicationListener","加载顺序","Profile","classpath","覆盖","优先级"],"medium","JavaSpring"],
["java-252","java","@SpringBootApplication 注解包含了哪三个注解？","@SpringBootConfiguration(等价@Configuration): 标注配置类。@EnableAutoConfiguration: 启用自动配置。@ComponentScan: 组件扫描(默认扫描当前包及子包)。exclude 属性可排除特定自动配置类。","@SpringBootApplication",["Java","Spring Boot","注解"],["@SpringBootApplication","@SpringBootConfiguration","@EnableAutoConfiguration","@ComponentScan","exclude","自动配置"],"easy","JavaSpring"],
["java-253","java","Spring Boot 中的 banner 怎么自定义？","resources/banner.txt 放置 ASCII art。关闭: spring.main.banner-mode=off。自定义: $ application.version}/application.formatted-version} 等占位符。图片: banner.gif/banner.jpg(自动转换)。","自定义 banner",["Java","Spring Boot","技巧"],["banner","banner.txt","ASCII","banner-mode","占位符","自定义","application.version"],"easy","JavaSpring/"],
["java-254","java","Spring Boot 的 @DependsOn 和 @Order 的区别？","@DependsOn: 控制 Bean 的初始化顺序(A 创建前先创建 B)。@Order: 控制注入集合时的顺序(@Autowired List<Bean> 按 @Order 排序)和控制 AOP/Filter 执行顺序。@DependsOn 是强依赖(没有B则A失败)，@Order 是弱排序。","@DependsOn vs @Order",["Java","Spring","注解"],["@DependsOn","@Order","初始化顺序","注入顺序","AOP","Filter","强依赖","弱排序"],"medium","JavaSpring"],
["java-255","java","Spring Boot 如何禁用特定的自动配置类？","@SpringBootApplication(exclude = {DataSourceAutoConfiguration.class})。application.yml: spring.autoconfigure.exclude=...。面试: 当你不需要某些自动配置时(如不用数据库但引入了 JDBC starter)。","禁用自动配置",["Java","Spring Boot","配置"],["exclude","自动配置","@SpringBootApplication","spring.autoconfigure.exclude","DataSourceAutoConfiguration","禁用"],"easy","JavaSpring"],
["java-256","java","Spring Boot 如何通过 Actuator 自定义 health 检查？","实现 HealthIndicator 接口或继承 AbstractHealthIndicator。health() 方法中检查依赖是否可用(DB/Redis/MQ)，返回 Health.up() 或 Health.down()。details: withDetail(reason,...) 附加详细信息。自定义 health 端点: management.endpoint.health.show-details=always。","自定义 Health",["Java","Spring Boot","Actuator"],["HealthIndicator","AbstractHealthIndicator","Health","Actuator","health","up","down","端点"],"medium","JavaSpring"],
["java-257","java","Spring Boot 的 @ConditionalOnExpression 怎么用？","SpEL 表达式控制 Bean 是否生效。@ConditionalOnExpression('${feature.enabled:false}')。@ConditionalOnExpression('!${feature.disabled:true}')。复杂条件: &&(false)、||(true)、!=。注意 SpEL 中 true/false 是字符串要加引号或用 Boolean。","@ConditionalOnExpression",["Java","Spring Boot","条件"],["@ConditionalOnExpression","SpEL","feature","条件","&&","||","字符串","Boolean"],"medium","JavaSpring"],

// 设计模式/多线程场景 (items 258-265)
["java-258","java","如何用 Java 实现一个简单的 Tomcat？","核心: ServerSocket 监听端口→accept() 获取 Socket→解析 HTTP 请求(请求行/请求头/请求体)→根据 URL 路由到对应的 Servlet→反射调用 service()→返回 HTTP 响应。线程池处理并发。核心类: Connector(连接器)+Container(容器)+Processor(处理器)。","手写 Mini Tomcat",["Java","网络编程","Web"],["Tomcat","ServerSocket","HTTP","Servlet","反射","线程池","Connector","Container"],"hard","JavaAdvanced"],
["java-259","java","如何实现一个带有超时和重试的 HTTP 客户端？","连接超时: Socket.connect(address, timeout)。读超时: Socket.setSoTimeout()。OkHttp3: connectTimeout/readTimeout。重试: 指数退避(1s→2s→4s)+最大重试次数。Retrofit: @Headers + 拦截器重试。只对幂等请求(GET/PUT)重试。","HTTP 客户端设计",["Java","网络","HTTP"],["HTTP客户端","超时","重试","指数退避","OkHttp","Retrofit","幂等","connectTimeout"],"medium","JavaAdvanced"],
["java-260","java","volatile 能保证 i++ 的原子性吗？为什么？","不能。i++ 是三个操作: 读→加1→写。volatile 只保证每个操作的可见性，不保证复合操作的原子性。多线程 i++ 需要 synchronized 或 AtomicInteger.incrementAndGet()。","volatile i++",["Java","并发","volatile"],["volatile","i++","原子性","AtomicInteger","CAS","读改写","复合操作"],"easy","JavaCore"],
["java-261","java","为什么 ConcurrentHashMap 的 key 和 value 不能是 null？","HashMap 允许一个 null key 和多个 null value。ConcurrentHashMap 不允许 null: 1) 二义性(ConcurrentHashMap 无法区分 key 不存在返回 null 还是 key 存在但 value 为 null) 2) Doug Lea 认为 null value 往往由 bug 产生，禁止 null 能及早暴露问题。","ConcurrentHashMap null",["Java","集合","并发"],["ConcurrentHashMap","null","HashMap","二义性","Doug Lea","bug","key","value"],"medium","JavaCore"],
["java-262","java","什么是 CopyOnWriteArrayList？适用于什么场景？","写时复制: 写操作(add/set/remove)加 ReentrantLock 锁，复制一份新数组，在新数组上修改，修改完再将引用指向新数组。读操作无锁。适合读多写少(如监听器列表)。缺点: 内存占用(写时复制)、数据实时性(读到旧数据)。","CopyOnWriteArrayList",["Java","集合","并发"],["CopyOnWriteArrayList","写时复制","ReentrantLock","读无锁","监听器","内存占用","实时性"],"medium","JavaCore"],
["java-263","java","SynchronousQueue 和 LinkedTransferQueue 的区别？","SynchronousQueue: 容量为0，put 必须等 take(一对一直接传递)。LinkedTransferQueue: 无界，支持 transfer()(阻塞直到被消费)和 tryTransfer()(非阻塞)。场景: SynchronousQueue 适合 Handoff(线程间传递)，CachedThreadPool 用它做任务队列。","SynchronousQueue",["Java","集合","并发"],["SynchronousQueue","LinkedTransferQueue","transfer","tryTransfer","Handoff","CachedThreadPool","无界","容量0"],"hard","JavaCore"],
["java-264","java","Java 中 notify 和 notifyAll 怎么选择？","notify: 随机唤醒一个等待线程。notifyAll: 唤醒所有等待线程。推荐 notifyAll: 避免信号丢失(错误唤醒的线程重新检查条件后继续 wait，不影响正确性)。notify 只在确定只有一个线程在等待且逻辑简单时使用。","notify vs notifyAll",["Java","并发","线程"],["notify","notifyAll","信号丢失","唤醒","wait","条件检查","随机"],"medium","JavaCore"],
["java-265","java","Java 中 CompletableFuture.allOf() 的异常处理？","allOf 不等待全部完成(只要有一个失败就返回)，不返回结果。异常: 被第一个异常中断。处理: 给每个 CompletableFuture 加 exceptionally() 自己处理异常，或者用 handle()。如果需要所有结果: allOf().join() 后遍历每个 future 用 get() 或 join() 取结果。","CompletableFuture.allOf",["Java","并发","异步"],["CompletableFuture","allOf","exceptionally","handle","join","get","异步","并行"],"medium","JavaCore"],

// 进阶面试 (items 266-275)
["java-266","java","Spring Boot 3.0 有哪些重要变化？","1) 最低 JDK17 2) Jakarta EE 9(javax→jakarta 包名迁移) 3) GraalVM Native Image 支持增强(AOT 编译) 4) 移除了 spring.factories(META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports 替代) 5) 默认启用 HTTP/3(HTTP2)。","Spring Boot 3.0",["Java","Spring Boot","新特性"],["Spring Boot 3.0","JDK17","Jakarta","GraalVM","AOT","spring.factories","HTTP3","javax"],"medium","JavaSpring"],
["java-267","java","Java 21 虚拟线程的调度原理？","虚拟线程(Virtual Thread) 是 JDK 的轻量级线程，由 JVM 调度而非 OS。每当虚拟线程执行阻塞操作(IO/sleep)，JVM 将载体线程(Carrier Thread)让给其他虚拟线程。不占用 OS 线程栈(默认几百字节)，允许创建百万级虚拟线程。ForkJoinPool 作为默认调度器。","虚拟线程调度",["Java","并发","JDK21","面试高频"],["虚拟线程","Virtual Thread","JDK21","Carrier Thread","ForkJoinPool","调度","百万并发","IO密集"],"hard","JavaCore"],
["java-268","java","Java 中 Pattern Matching for switch 怎么用？","JDK21 支持: switch(obj) { case Integer i -> ...; case String s -> ...; case null -> ...; }。类型匹配后变量直接可用。利用 Sealed 类型可编译期检查覆盖度: switch(sealedType) 编译器能判断是否覆盖所有子类(不需要 default 分支)。","Pattern Matching switch",["Java","JDK21","新特性"],["Pattern Matching","switch","JDK21","Sealed","类型匹配","null","编译期检查","全覆盖"],"medium","JavaCore"],
["java-269","java","Reactive Streams 规范和 Reactor 的核心概念？","Reactive Streams: Publisher(发布者)、Subscriber(订阅者)、Subscription(订阅关系)、Processor(中间处理)。Reactor: Mono(0-1元素)和Flux(0-N元素)。背压: request(n)控制流速。操作符: map/flatMap/filter/zip/merge。响应式适合高并发IO密集场景(如 Gateway)。","Reactive Streams",["Java","响应式","Reactor"],["Reactive","Reactor","Mono","Flux","背压","Publisher","Subscriber","Subscription","Gateway"],"medium","JavaAdvanced"],
["java-270","java","Spring 的 @Lookup 注解有什么作用？","@Lookup 方法注入: 单例 Bean 中注入原型 Bean，每次调用 @Lookup 注解的方法都返回新的原型 Bean 实例。CGLIB 代理生成方法体。abstract 方法: 返回类型为原型 Bean。替代: ObjectFactory/Provider 注入。","@Lookup 注入",["Java","Spring","注入"],["@Lookup","方法注入","单例","原型","CGLIB","ObjectFactory","Provider","abstract"],"medium","JavaSpring"],
["java-271","java","Spring 中 @EventListener 和 @TransactionalEventListener 的区别？","@EventListener: 事件发布后立即执行监听器(同步默认)。@TransactionalEventListener: 绑定事务阶段(默认 AFTER_COMMIT 事务提交后执行)。phase: BEFORE_COMMIT/AFTER_COMMIT/AFTER_ROLLBACK/AFTER_COMPLETION。场景: 注册后发邮件应该等事务提交成功后再发。","@TransactionalEventListener",["Java","Spring","事件","事务"],["@TransactionalEventListener","@EventListener","AFTER_COMMIT","事务","事件","同步","异步","BEFORE_COMMIT"],"medium","JavaSpring"],
["java-272","java","Java 中 WeakHashMap 的使用场景和注意事项？","WeakHashMap: key 是弱引用，当 key 不再被外部强引用且发生 GC 时，对应的键值对自动删除。适合: 元数据缓存(如线程本地数据)。注意: value 如果是强引用会导致 key 无法回收。典型场景: Tomcat 缓存 Session 对应信息。","WeakHashMap",["Java","集合","弱引用"],["WeakHashMap","弱引用","GC","缓存","Session","Tomcat","元数据","自动删除"],"medium","JavaCore"],
["java-273","java","如何设计一个分布式定时任务？","核心: 多节点只执行一次。实现: 1)分布式锁(Redis SETNX/Redisson)保证单节点执行 2) DB 唯一约束(任务+时间) 3) Elastic-Job(当当)分片执行 4) XXL-JOB(调度中心+执行器)。选型: 轻量用 ShedLock(Redis/DB 锁)，复杂用 XXL-JOB。","分布式定时任务",["Java","分布式","任务调度"],["分布式定时任务","ShedLock","XXL-JOB","Elastic-Job","Redis","SETNX","分片","调度中心"],"medium","JavaAdvanced"],
["java-274","java","Java 中如何安全地停止一个线程？","interrupt() 设置中断标志位(不强制停止)。线程内: isInterrupted() 检查标志位并自行退出循环，或 catch InterruptedException 并退出。Thread.stop() 已废弃(不安全: 释放所有锁导致对象状态不一致)。推荐: 标志位+interrupt 配合。","安全停止线程",["Java","并发","线程"],["interrupt","stop","isInterrupted","InterruptedException","标志位","废弃","不安全","退出"],"easy","JavaCore"],
["java-275","java","Java 中线程的上下文切换开销有多大？如何减少？","上下文切换: 内核态切换、保存/恢复寄存器、刷新 TLB。开销约 1-10μs。减少: 1)无锁编程(CAS/Atomic) 2)协程(虚拟线程/Quasar) 3)减少线程数(小于CPU核数*2) 4)使用单线程模型(Netty/Redis) 5)批量处理减少切换频率。","上下文切换优化",["Java","并发","性能"],["上下文切换","TLB","CAS","虚拟线程","协程","单线程","Netty","批量","CPU核数"],"medium","JavaCore"],
];
let count = 0;
for (const [id, deckId, question, answer, title, tags, skw, difficulty, sub] of cards) {
  try {
    await prisma.card.create({ data: { id, deckId, type: "qa", question, answer, title, tags: JSON.stringify(tags), searchKeywords: JSON.stringify(skw || []), difficulty, source: "manual", subTopic: sub || null } });
    count++;
  } catch(e: any) { if (!e.message?.includes("Unique")) console.warn("Skip " + id); }
}
console.log("Inserted " + count + " / " + cards.length + " cards");
await prisma.$disconnect();
}
main();
