import prisma from "../db/prisma";

async function main() {
const cards: Array<[string,string,string,string,string,string[],string[],string,string]> = [
["agent-30","agent","什么是 AI Agent？和传统程序的区别？","AI Agent 是具有自主决策能力的智能体，能感知环境、制定计划、调用工具、执行动作并反思调整。与传统程序区别: 传统程序按固定流程执行，Agent 根据目标和环境动态规划。核心组件: LLM(大脑)、Planning(规划)、Memory(记忆)、Tools(工具)。","AI Agent 定义",["Agent","AI","LLM"],["Agent","AI Agent","自主","规划","记忆","工具","传统程序","LLM"],"medium","AgentCore"],
["agent-31","agent","Agent 的四种核心能力是什么？","1)感知(Perception): 理解用户意图和环境(context) 2)规划(Planning): 制定达成目标的执行计划(Plan) 3)执行(Action): 调用工具(Tools/API)实现计划 4)反思(Reflection): 评估执行结果，调整后续行动。ReAct = Reasoning + Acting。","Agent 核心能力",["Agent","AI","LLM"],["Agent","感知","规划","执行","反思","ReAct","Planning","Action","Reflection"],"medium","AgentCore"],
["agent-32","agent","什么是 ReAct 模式？和 CoT 的区别？","ReAct(Reasoning + Acting): Thought→Action→Observation 循环。每步先思考再行动，观察结果后调整。CoT(Chain of Thought): 纯推理链路，不调用外部工具。ReAct 适合需要外部信息的任务(查资料/调用API/搜索)，CoT 适合纯推理任务(数学/逻辑)。","ReAct 模式",["Agent","ReAct","LLM"],["ReAct","CoT","Reasoning","Acting","Observation","Thought","Action","Tool","反思"],"hard","AgentCore"],
["agent-33","agent","Agent 的记忆（Memory）有哪些类型？","1)短期记忆(Short-term): 对话上下文(context window)，有限长度，超出则遗忘 2)长期记忆(Long-term): 持久化存储知识/经验，RAG 检索或向量数据库 3)工作记忆(Working): 当前任务状态、中间结果。实现: 向量数据库(Pinecone/Qdrant/Chroma)+摘要压缩。","Agent 记忆",["Agent","Memory","LLM"],["Agent","记忆","短期记忆","长期记忆","工作记忆","向量数据库","RAG","context window","摘要"],"medium","AgentCore"],
["agent-34","agent","Agent 的工具调用（Tool Use/Function Calling）原理？","LLM 根据 prompt 判断需要调用哪个工具→输出结构化 JSON(func+args)→Agent 执行工具→结果返回 LLM 继续推理。OpenAI: function_call 参数。LangChain: @tool 装饰器定义工具。Tool 定义需要 name、description、parameters(schema)。","Tool Use 原理",["Agent","Function Calling","Tool"],["Agent","Tool Use","Function Calling","OpenAI","LangChain","@tool","JSON","schema","参数"],"medium","AgentCore"],
["agent-35","agent","RAG（检索增强生成）的完整流程是什么？","离线阶段: 文档加载→文本分割(Chunking)→Embedding(向量化)→向量数据库存储。在线阶段: 用户问题→Embedding→向量检索(相似度TopK)→组装 Prompt(问题+检索到的文档)→LLM 生成答案。核心价值: 外挂知识库，减少幻觉，实时更新知识。","RAG 完整流程",["Agent","RAG","LLM"],["RAG","检索增强生成","Embedding","向量数据库","Chunking","相似度","幻觉","知识库"],"medium","AgentRAG"],
["agent-36","agent","RAG 中的 Chunking 策略有哪些？怎么选？","固定长度: 简单但可能截断语义。句子分割: 按句号/换行切分，保留语义完整。语义分割: 用 embedding 相似度判断切分点(相似度骤降处切分)。递归分割: 先按段落→再按句子→再按字符(优先保留大粒度)。重叠(Overlap): 相邻 chunk 重叠 10-20%，避免上下文断裂。","RAG Chunking",["Agent","RAG","Chunking"],["RAG","Chunking","分块","固定长度","句子分割","语义分割","重叠","Overlap","递归"],"medium","AgentRAG"],
["agent-37","agent","RAG 的 Naive/Advanced/Modular 三代演进？","Naive RAG: 简单的 Retrieve→Read 流程。Advanced RAG: 加入检索前处理(Query Rewriting)、检索后处理(Re-ranking)、多路检索(Hybrid Search)。Modular RAG: 可插拔组件(不同的 Retriever/Generator/Re-ranker 可以灵活组合)。大多数生产系统是 Advanced RAG。","RAG 三代演进",["Agent","RAG","LLM"],["RAG","Naive RAG","Advanced RAG","Modular RAG","Query Rewriting","Re-ranking","Hybrid Search","多路检索"],"medium","AgentRAG"],
["agent-38","agent","RAG 中常见的检索策略有哪些？","稀疏检索: BM25/TF-IDF 关键词匹配(FTS5/Elasticsearch)。稠密检索: Embedding 向量相似度(cosine)。混合检索(Hybrid): 稀疏+稠密+重排序。多阶段检索: 粗排(快速召回Top100)→精排(重排序Top10)。父文档检索: 检索小 chunk，返回大 chunk 或原始文档。","RAG 检索策略",["Agent","RAG","检索"],["RAG","检索","稀疏检索","稠密检索","Hybrid","BM25","重排序","多阶段","父文档"],"medium","AgentRAG"],
["agent-39","agent","RAG 中如何评估检索质量？","检索指标: Recall@K、Precision@K、MRR(平均倒数排名)、nDCG(归一化折损累计增益)。生成指标: Faithfulness(忠实度)、Answer Relevance(答案相关性)。评估框架: RAGAS、TruLens、LangSmith。","RAG 评估",["Agent","RAG","评估"],["RAG","评估","Recall@K","MRR","nDCG","Faithfulness","RAGAS","TruLens","检索质量"],"medium","AgentRAG"],
["agent-40","agent","RAG 中 Query Rewriting 的作用和方法？","Query Rewriting 解决用户问题表述不精确的问题。方法: 1)HyDE: 先让 LLM 生成假设答案→用假设答案去检索 2)多 Query 生成: 生成多个不同表述的 Query 并行检索→合并结果 3)Step-back: 生成更抽象的上层问题辅助检索 4)Query2Doc: 生成伪文档扩展。","Query Rewriting",["Agent","RAG","检索"],["RAG","Query Rewriting","HyDE","多Query","Step-back","Query2Doc","检索优化","伪文档"],"hard","AgentRAG"],
["agent-41","agent","什么是 Agentic RAG？和传统 RAG 的区别？","传统 RAG: 用户问→检索→生成答案(一次性)。Agentic RAG: Agent 自主决策是否检索、检索什么、是否需要多次检索、是否需要切换检索源。特点: 多步推理、自适应检索策略、工具组合。如先检索→发现信息不足→改写 Query 再检索→对比多个来源→综合生成。","Agentic RAG",["Agent","RAG","LLM"],["Agentic RAG","多步推理","自适应","检索策略","工具组合","多轮","自主决策"],"hard","AgentRAG"],
["agent-42","agent","RAG 中的 Re-ranking 模型有哪些？","bge-reranker-v2-m3: BGE 重排序模型(中英双语)。Cohere Rerank: 商业 API。Cross-Encoder: 全注意力计算 query-doc 对(比双塔更准但更慢)。ColBERT: 延迟交互(Late Interaction)折中方案。LLM-based Rerank: 用 LLM 评分(query, doc)对的相关性。","Re-ranking 模型",["Agent","RAG","检索"],["RAG","Re-ranking","bge-reranker","Cohere","Cross-Encoder","ColBERT","LLM Rerank","重排序"],"hard","AgentRAG"],
["agent-43","agent","Multi-Agent 系统是什么？与单 Agent 的区别？","Multi-Agent: 多个 Agent 分工协作完成复杂任务。角色: 规划Agent、执行Agent、审查Agent、专家Agent。通信: 消息传递(LangGraph 状态图)或共享记忆。优势: 分工明确(每个Agent专注于自己的任务)、容错(单个Agent失败不影响整体)、可扩展。","Multi-Agent 系统",["Agent","多Agent","LLM"],["Multi-Agent","协作","分工","LangGraph","状态图","规划Agent","执行Agent","审查Agent"],"medium","AgentArchitecture"],
["agent-44","agent","LangChain 的核心组件有哪些？","Model I/O: LLM/ChatModel+PromptTemplate。Retrieval: Document Loader+Text Splitter+Embedding+VectorStore+Retriever。Chains: 串联多个组件。Agents: 根据 LLM 输出决定动作(Tool Calling)。Memory: 记录对话历史。Callbacks: 日志/监控/流式输出。","LangChain 组件",["Agent","LangChain","LLM"],["LangChain","Model I/O","Retrieval","Chains","Agents","Memory","Callbacks","PromptTemplate"],"medium","AgentFramework"],
["agent-45","agent","LangGraph 是什么？和 LangChain 的关系？","LangGraph 是 LangChain 的 Agent 编排框架。把 Agent 流程建模为有向图: 节点(Agent/Function/LLM)+边(条件边/普通边)。状态管理: 图的状态在节点间传递。支持: 循环(Agent 多步推理)、条件分支(if-else)、人工介入(Human-in-the-loop)。","LangGraph 介绍",["Agent","LangGraph","LLM"],["LangGraph","LangChain","有向图","节点","边","状态管理","循环","条件分支","Human-in-the-loop"],"medium","AgentFramework"],
["agent-46","agent","CrewAI 的多 Agent 协作模式？","CrewAI 模拟团队协作: 定义 Agent(角色Role+目标Goal+背景Backstory)→分配任务(Task+expected_output)→组成 Crew→kickoff() 执行。顺序执行(Sequential)或层级执行(Hierarchical)。每个 Agent 可以使用不同工具。适合复杂研究/分析任务。","CrewAI 介绍",["Agent","CrewAI","多Agent"],["CrewAI","Agent","Crew","Task","Role","Goal","sequential","hierarchical","协作"],"medium","AgentFramework"],
["agent-47","agent","AutoGPT 和 BabyAGI 的架构特点？","AutoGPT: 自主 Agent，给定目标自己分解任务，互联网搜索+文件读写+代码执行，会无限循环直至目标完成。BabyAGI: 任务驱动的 Agent，创建任务列表→优先级排序→逐一执行→生成新任务。两者都基于 ReAct 循环，但 AutoGPT 更强调自主性。","AutoGPT/BabyAGI",["Agent","AutoGPT","BabyAGI"],["AutoGPT","BabyAGI","自主","任务分解","ReAct","优先级","循环","搜索"],"medium","AgentFramework"],
["agent-48","agent","Agent 的 Planning 有哪些方法？","Task Decomposition: 复杂任务拆分为子任务(Chain of Thought/Tree of Thought)。Plan-and-Execute: 先生成完整计划→逐步执行→根据结果调整。ReWOO: Reason without Observation(规划时不依赖工具结果)。LLMCompiler: 并行执行无依赖的子任务。","Agent Planning 方法",["Agent","Planning","LLM"],["Agent","Planning","Task Decomposition","Plan-and-Execute","ReWOO","LLMCompiler","CoT","ToT"],"hard","AgentCore"],
["agent-49","agent","Agent 如何自我反思和纠错？","Self-Reflection: 每次动作后评估结果是否符合预期。Reflexion: 失败后总结教训存入长期记忆。Self-Critique: 让 Agent 评价自己的输出。投票: 多个 Agent 对同一问题给出答案，投票选择。验证器: 用规则或另一 LLM 验证 Agent 输出。","Agent 自我反思",["Agent","Self-Reflection","LLM"],["Agent","自我反思","Reflexion","Self-Critique","投票","验证器","纠错","教训"],"medium","AgentCore"],
["agent-50","agent","Agent 的安全问题有哪些？如何防范？","Prompt Injection: 用户输入恶意 prompt 劫持 Agent。越权: Agent 调用了不该调用的工具。数据泄露: Agent 把敏感信息发到外部。幻觉: Agent 编造了不存在的操作结果。防范: 输入过滤、权限控制(最小权限原则)、工具白名单、Human-in-the-loop 审核。","Agent 安全",["Agent","安全","LLM"],["Agent","安全","Prompt Injection","越权","数据泄露","幻觉","权限控制","白名单","Human-in-the-loop"],"medium","AgentSafety"],
["agent-51","agent","什么场景适合用 Agent？什么场景不适合？","适合: 需要多步推理的复杂任务(研究/分析)、需要调用多种工具(搜索+计算+API)、开放性任务(没有固定流程)。不适合: 简单 CRUD(用传统 API 更快)、确定性高的任务(规则引擎)、对延迟敏感(Agent 需要多次 LLM 调用)、成本敏感(每次推理消耗 token)。","Agent 适用场景",["Agent","场景","选型"],["Agent","场景选择","复杂任务","多步推理","CRUD","延迟","成本","规则引擎","选型"],"medium","AgentCore"],
["agent-52","agent","Function Calling 的 JSON Schema 如何定义？","定义工具的 name、description(描述工具作用)、parameters(type=object+properties+required)。properties 每个参数: type(string/number/boolean)、description(描述参数)、enum(可选值)。OpenAI: tools=[{type:function,function:{...}}]。强制 JSON 输出: response_format={type:json_object}。","Function Calling Schema",["Agent","Function Calling","JSON"],["Function Calling","JSON Schema","OpenAI","tools","parameters","properties","required","enum","json_object"],"medium","AgentCore"],
["agent-53","agent","什么是 GraphRAG？和传统 RAG 的区别？","GraphRAG 用知识图谱增强 RAG: 实体和关系存在图中。检索时不仅查文本，还查关联实体、邻居节点、多跳关系。优势: 回答实体之间关系类问题更准确。构建: 用 LLM 从文本中提取实体+关系→构建图→社区摘要→Graph+文本混合检索。","GraphRAG 介绍",["Agent","RAG","知识图谱"],["GraphRAG","知识图谱","RAG","实体","关系","社区摘要","多跳","图检索"],"hard","AgentRAG"],
["agent-54","agent","向量数据库选型：Milvus vs Qdrant vs Chroma vs Pinecone？","Milvus: 分布式、高性能、GPU 索引、适合 10 亿级。Qdrant: Rust 编写、高性能、过滤丰富、本地/云都可。Chroma: 轻量级、Python 原生、适合开发原型。Pinecone: 托管云服务、免运维。Weaviate: GraphQL 原生支持。选型: 原型用 Chroma，生产用 Milvus/Qdrant，免运维用 Pinecone。","向量数据库选型",["Agent","RAG","向量数据库"],["向量数据库","Milvus","Qdrant","Chroma","Pinecone","Weaviate","选型","GPU","原型","生产"],"medium","AgentRAG"],
["agent-55","agent","Embedding 模型怎么选？bge vs text-embedding vs e5？","bge-m3: 中英双语、1024维、MTEB 榜单 Top。text-embedding-3-small/large(OpenAI): 商业级、1536/3072维。e5-mistral: Mistral 微调版。选型: 中文场景优先 bge-m3，商业项目用 OpenAI。维度影响: 高维度精度高但存储和检索慢。Matryoshka: 支持截断维度。","Embedding 选型",["Agent","RAG","Embedding"],["Embedding","bge-m3","OpenAI","e5","维度","MTEB","Matryoshka","中文","选型"],"medium","AgentRAG"],
["agent-56","agent","Prompt Engineering 的核心技巧有哪些？","Few-shot: 提供示例。Chain-of-Thought: 引导逐步推理。Role Playing: 赋予角色。结构化输出: 要求 JSON/Markdown 格式。Constraints: 设定边界(字数/格式)。Negative Prompt: 明确不要什么。Dynamic Prompt: 根据上下文动态组装。","Prompt Engineering",["Agent","Prompt","LLM"],["Prompt","Few-shot","CoT","Role Playing","结构化输出","Constraints","N-Prompt","Dynamic Prompt"],"medium","AgentCore"],
["agent-57","agent","如何评估 LLM 输出质量？自动评估 vs 人工评估？","自动评估: ROUGE(文本摘要)、BLEU(翻译)、BERTScore(语义相似度)。LLM-as-Judge: 用 GPT-4 评估(如 G-Eval)。人工评估: 盲评、A/B 测试。组合: 快速迭代用自动评估，上线前人工抽检。RAGAS: 专门评估 RAG 输出的框架(Faithfulness/Answer Relevance)。","LLM 评估",["Agent","评估","LLM"],["LLM","评估","ROUGE","BLEU","BERTScore","LLM-as-Judge","RAGAS","人工评估","A/B测试"],"medium","AgentCore"],
["agent-58","agent","什么是 Prompt Injection？如何防御？","Prompt Injection: 用户输入恶意 prompt 覆盖系统指令。如: 用户说 ignore all previous instructions。防御: 1)分隔符(用特殊标记分隔系统 prompt 和用户输入) 2)输入过滤 3)指令优先级(明确声明系统指令不可覆盖) 4)输出检查。","Prompt Injection",["Agent","安全","Prompt"],["Prompt Injection","注入攻击","ignore","分隔符","输入过滤","优先级","防御","输出检查"],"medium","AgentSafety"],
["agent-59","agent","什么是 RLHF（人类反馈强化学习）？","RLHF 三个阶段: 1)SFT(监督微调): 用人类标注的高质量回答微调模型 2)Reward Model: 人类对多个回答排序，训练奖励模型 3)PPO: 用奖励模型通过强化学习优化 LLM 输出。InstructGPT/ChatGPT 都用了 RLHF。价值: 让模型输出更符合人类偏好。","RLHF 原理",["Agent","LLM","训练"],["RLHF","SFT","Reward Model","PPO","人类反馈","ChatGPT","InstructGPT","排序","偏好"],"hard","AgentCore"],
["agent-60","agent","Agent 的 Token 消耗怎么优化？","1)减少 prompt 长度(摘要压缩历史) 2)缓存相似请求的响应 3)选择合适的模型(小模型做简单任务) 4)批量调用(batch API) 5)Prompt 精简 6)使用 Function Calling 代替长文本生成。成本计算: input_token * input_price + output_token * output_price。","Agent Token 优化",["Agent","成本","Token"],["Agent","Token","成本","缓存","prompt","批量","Function Calling","摘要","小模型"],"medium","AgentCore"],
["agent-61","agent","什么是 AI 可观测性？LangSmith 和 LangFuse 怎么用？","AI 可观测性: 追踪 LLM 调用的输入/输出/token/延迟/成本。LangSmith(LangChain 官方): 自动记录所有 Chain/Agent 的运行轨迹。LangFuse(开源): 自部署，支持 LangChain/LlamaIndex。功能: trace 查看调用链、evaluation 评估质量、playground 调试 prompt。","AI 可观测性",["Agent","监控","LangSmith"],["AI可观测性","LangSmith","LangFuse","trace","evaluation","playground","cost","延迟","prompt调试"],"medium","AgentFramework"],
["agent-62","agent","什么是 Model Context Protocol (MCP)？","MCP 是 Anthropic 提出的 Agent 和工具间的开放协议。Client-Server 架构: Host(Claude/IDE)→Client→Server(工具提供方)。标准化: 工具发现(lists/tools)、调用(call_tool)、资源读取(resource)、Prompt 模板。好处: 一次编写工具，多个 LLM 复用。","MCP 协议",["Agent","MCP","协议"],["MCP","Model Context Protocol","Anthropic","Client","Server","工具发现","call_tool","标准化"],"medium","AgentFramework"],
["agent-63","agent","Agent 的流式输出(Streaming)怎么实现？","Server-Sent Events(SSE): LLM 逐 token 推送。前端: EventSource 或 fetch+ReadableStream。LangChain: chain.stream(input) 返回迭代器。用户体验: 打字机效果提升感知速度。思考过程: 先流式输出 Thought，再输出 Action。","Agent 流式输出",["Agent","Streaming","SSE"],["Agent","流式","SSE","Server-Sent Events","ReadableStream","打字机","LangChain","stream","Thought"],"medium","AgentCore"],
["agent-64","agent","LlamaIndex 的核心概念是什么？","LlamaIndex 是 RAG 数据框架。核心: Document(原始文档)→Node(分块后节点)→Index(结构: VectorIndex/SummaryIndex/TreeIndex)→Retriever(检索)→QueryEngine(查询引擎)→Response(生成答案)。Router: 根据问题类型路由到不同 Index。","LlamaIndex 介绍",["Agent","RAG","LlamaIndex"],["LlamaIndex","Document","Node","Index","Retriever","QueryEngine","Router","Agent"],"medium","AgentFramework"],
["agent-65","agent","Dify 和 Coze 是什么？低代码 Agent 平台？","Dify: 开源 LLM 应用平台，可视化编排 RAG+Agent 工作流，支持多种 LLM/向量库。Coze(字节): 低代码 Agent 构建平台，拖拽式 bot 开发。共同点: 降低 AI 应用开发门槛、可视化 workflow、内置插件市场。适合: 快速验证想法、非技术团队、简单场景。","Dify/Coze 平台",["Agent","低代码","Dify"],["Dify","Coze","低代码","Agent","可视化","workflow","开源","插件"],"medium","AgentFramework"],
["agent-66","agent","什么是 LLM 的幻觉(Hallucination)？RAG 怎么减少幻觉？","幻觉: LLM 生成的内容看似合理但事实错误。分类: 内在幻觉(自相矛盾)、外在幻觉(与事实不符)。RAG 减少幻觉: 检索真实文档作为 ground truth→限制 LLM 基于检索内容回答→不编造。其他方法: Temperature 降低(更确定)、约束输出格式、事实核查。","LLM 幻觉",["Agent","LLM","RAG"],["LLM","幻觉","Hallucination","RAG","ground truth","Temperature","事实核查","检索"],"medium","AgentRAG"],
["agent-67","agent","RAG 中如何处理多模态文档(PDF/图片/表格)？","PDF: PyMuPDF/pdfplumber 提取文字+表格。图片: OCR(Tesseract/PaddleOCR)→文字→Embedding。表格: 转 Markdown 或 JSON 格式保留结构。Unstructured.io: 统一文档解析库支持多种格式。多模态 Embedding: CLIP(图文)、BridgeTower。","RAG 多模态",["Agent","RAG","多模态"],["RAG","多模态","PDF","OCR","表格","Unstructured","CLIP","BridgeTower","Markdown"],"hard","AgentRAG"],
["agent-68","agent","Agent 如何处理长上下文？","1)摘要压缩: 对历史对话做摘要 2)滑动窗口: 只保留最近 N 轮 3)向量检索: 把历史对话存入向量库，检索相关片段 4)MemGPT: 操作系统式内存管理(内存分页、换入换出) 5)分级摘要: 近期对话详细+远期对话摘要。","长上下文处理",["Agent","Memory","LLM"],["Agent","长上下文","摘要","滑动窗口","向量检索","MemGPT","分级摘要","context window","压缩"],"medium","AgentCore"],
["agent-69","agent","什么是 Self-RAG？和传统 RAG 的区别？","Self-RAG: LLM 在生成答案时自主决定是否需要检索、检索什么、检索结果是否相关、是否需要进一步检索。通过特殊 token(Retrieve/IsREL/IsSUP/IsUSE)控制流程。传统 RAG 总是检索，Self-RAG 按需检索。减少无关检索，提高答案质量。","Self-RAG",["Agent","RAG","Self-RAG"],["Self-RAG","RAG","按需检索","Retrieve","IsREL","IsSUP","IsUSE","特殊token"],"hard","AgentRAG"],
["agent-70","agent","RAG 系统中如何处理检索失败的情况？","1)降级回答: 检索结果为空时告知用户无相关信息或退回纯 LLM 回答 2)多路检索: 同时查多个向量库/关键词搜索增加命中率 3)扩大检索范围: 如果 TopK 结果相关性都低，增加 K 或调整阈值 4)Query Rewriting: 改写问题重新检索。","RAG 检索失败",["Agent","RAG","容错"],["RAG","检索失败","降级","多路检索","Query Rewriting","扩大范围","无相关","阈值"],"medium","AgentRAG"],
["agent-71","agent","什么是 Agent-as-a-Judge？","用 Agent 作为评估器。评分标准: Rubric(评分准则)定义每级标准。过程: Agent 读取对话历史→按 Rubric 打分→给出理由。优势: 比简单指标(ROUGE/BLEU)更贴近人工判断。方法: G-Eval(LLM 评估)、MT-Bench(多轮对话评分)。","Agent-as-Judge",["Agent","评估","LLM"],["Agent","Judge","G-Eval","MT-Bench","Rubric","评分","对话","评估器"],"medium","AgentCore"],
];
let count = 0;
for (const [id, deckId, question, answer, title, tags, skw, difficulty, sub] of cards) {
  try { await prisma.card.create({ data: { id, deckId, type:"qa", question, answer, title, tags: JSON.stringify(tags), searchKeywords: JSON.stringify(skw), difficulty, source:"manual", subTopic: sub||null } }); count++; } catch(e: any) {}
}
const total = await prisma.card.count({where:{deckId:"agent"}});
console.log("Inserted "+count+", total Agent: "+total);
await prisma.$disconnect();
}
main();
