[package]
name = "interview-flashcards"
version = "0.6.0"
description = "面经闪卡 - Interview Flashcards"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "interview_flashcards_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2", features = [] }
tauri-plugin-log = "2"
dirs-next = "2.0"
libc = "0.2"
rfd = "0.15"
